apps/wss/src/index.ts
apps/wss/src/server.ts

Because they were getting consumed by a subscription to trigger messages in another environment. Fixed this by adding the api key to the subscription name.

Fixed issue where workflow runs weren’t starting

---

apps/webapp/.storybook/main.ts

Fix storybook root alias by removing trailing slashes. Relevant Slack thread: https://mirrorful-internal.slack.com/archives/C052XABLB3M/p1683658526450009?thread_ts=1682966586.286049&cid=C052XABLB3M

Fix storybook root alias by removing trailing slashes

---

apps/webapp/app/presenters/EnvironmentsStreamPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.environments.stream/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.environments/route.tsx
apps/webapp/app/utils/pathBuilder.ts

PR to add live refreshing to the **Environments & API Key** page.
I followed a similar pattern to what we do on the **Run** page. The key part of this PR is correctly determining _when_ to refresh the page. I expanded on the logic found in the [Environment endpoint stream sse loader](https://github.com/triggerdotdev/trigger.dev/blob/main/apps/webapp/app/routes/resources.environments.%24environmentParam.endpoint.stream.ts#L32). That `sse` implementation seems to handle calculating a diff between a _single_ environment. I expanded on that and recreated the same thing for _multiple_ environments (i.e. all the environments that appear on the **Environments & API Key** page).
1. I spun up the trigger.dev app locally
2. I created a new NextJS app locally
3. I followed the [trigger dev …

feat: 🎸 add live refreshing to Environments & API key page

---

apps/webapp/app/components/navigation/ProjectsMenu.tsx

PR to add a project job count pill component to the project menu in the breadcrumb.
Bounty: /claim https://github.com/triggerdotdev/trigger.dev/issues/192

feat: 🎸 add project job count pill to breadcrumb project menu

---

apps/webapp/app/models/organization.server.ts

PR to filter out internal jobs in the `getOrganizaions` call. I did the filtering in the actual prisma call so that the correct count propagates throughout the app. The change should be reflected in the following places:
1. The home page org list
2. The project page for a given org
3. The breadcrumb project menu once #195 is implemented
/claim #193

feat: 🎸 filter organization > project > jobs to internal=false

---

apps/webapp/package.json
docker/Dockerfile
docker/scripts/entrypoint.sh

PR to remove global packages for DB migrations in the Dockerfile.
Executing the migrations by directly using the `db:migrate:deploy` script in the `@trigger.dev/database` package.
Instead of using `ts-node`, I'm using `esbuild` to bundle the `seed.ts` file and its dependencies into a `seed.js` file in the `builder` Dockerfile stage. Then we can just copy over the built `seed.js` file into the final Dockerfile layer and execute that file instead with `node`. Bundling the file like this requires us to copy over the `schema.prisma` schema file and the `libquery_engine-linux-arm64-openssl-1.1.x.so.node` prisma engine file to the `~/webapp/prisma` directory so that the bundled file can access external dependencies correctly.
I verified this by adding a `webapp` service to the …

chore: 🤖 improve migrations for docker container startup

---

.changeset/mighty-gorillas-march.md
apps/webapp/app/models/organization.server.ts
packages/cli/package.json
packages/cli/src/commands/init.ts
pnpm-lock.yaml

fixes #190 
/claim #190
1. I followed the instructions to setup trigger.dev in my local NextJS app pointing to my local trigger.dev fork and reproduced the error.
2.  I traced the code and found the location of the path causing the issue.
3. I added url from npm to use pathToFileURL to convert the path to one that would be valid on windows.
1. I spun up the trigger.dev app locally
2. I created a new NextJS app locally 
3. I ran the init command in the cli from my updated code for the cli in my local Next app and confirmed that the installation no longer aborted due to path issues

[TRI-699] using pathToFileURL on path used in detectPagesOrAppDir

---

.changeset/dry-poems-joke.md
packages/cli/package.json
packages/cli/src/commands/init.ts
pnpm-lock.yaml

PR to replace the `tsconfig` package with the `tsconfck` package. I tested this by building the CLI tool locally and initializing a new NextJS project with a `tsconfig.js` file that has trailing commas.
Bounty: /claim #211

chore: 🤖 replace tsconfig package with tsconfck package

---

.changeset/tender-sloths-lay.md
examples/nextjs-example/src/jobs/github.ts
integrations/github/src/tasks.ts

Fixes #201 
Added following git database tasks for github integration
/claim #201

feat: added git database tasks for github integration

---

.changeset/blue-monkeys-speak.md
packages/cli/src/commands/dev.ts

Fixes #210
/claim #210
Detect if a Next.js project is running on the specified port before opening a tunnel

Feat: Detect if a Next.js project is running on the specified port before opening a tunnel

---

.env.example
CONTRIBUTING.md
apps/webapp/app/env.server.ts
apps/webapp/app/routes/api.v1.integrations.$integrationSlug.connections.$connectionId.ts
apps/webapp/app/services/externalApis/integrationAuthRepository.server.ts
apps/webapp/app/services/externalApis/oauth2.server.ts
apps/webapp/app/services/secrets/secretStore.server.ts
packages/database/prisma/migrations/20230731145332_add_version_to_secret_store/migration.sql
packages/database/prisma/schema.prisma

Uses the `aes-256-gcm` symmetric algorithm to encrypt values in the SecretStore. I added a "version" field to the SecretStore, with "1" meaning the old non-encrypted value, and a new version "2" that is the encrypted variant. Updating a secret that was previously version 1 will upgrade it to version 2, but otherwise version 1 SecretStore records will remain unencrypted (well, they are encrypted at rest in AWS). Stores the IV/nonce and the tag alongside the ciphertext (the encrypted data) in the value field instead of the raw value.

feat: encrypt values in SecretStore using an encryption key

---

.changeset/cool-snakes-deny.md
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.environments/FirstEndpointSheet.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.environments/route.tsx
apps/webapp/app/routes/resources.projects.$projectId.endpoint.ts
apps/webapp/app/services/endpointApi.server.ts
apps/webapp/app/services/endpoints/createEndpoint.server.ts
apps/webapp/app/services/endpoints/indexEndpoint.server.ts
apps/webapp/app/services/endpoints/validateCreateEndpoint.server.ts
apps/webapp/app/services/runs/performRunExecution.server.ts
apps/webapp/app/services/sources/deliverHttpSourceRequest.server.ts
apps/webapp/app/services/triggers/initializeTrigger.server.ts
packages/core/src/schemas/api.ts
packages/trigger-sdk/src/triggerClient.ts

The only way (before this PR) to add an endpoint was to use the CLI. This can be problematic for certain use cases, particularly if you want to add the PROD environment first.
The blank state of a project's environment page now has a button "Add your first endpoint".
You can select the environment and the URL for your endpoint. Submitting the form creates the endpoint.
The `EndpointApi` class required an `id` in the constructor. This was only used in the `ping()` method.
There are two options:
1. Remove the `id` from the constructor, and just pass it in to the methods that need it, e.g. ping().
2. Create a different client that doesn't require the id.
3. Make the id optional, this feels like a bad choice because it breaks the type safety.
First of all I implemented 2, a new client. Then …

Add your first endpoint in the dashboard

---

.changeset/unlucky-wombats-scream.md
packages/cli/src/utils/detectNextJsProject.ts
packages/cli/src/utils/readPackageJson.ts

There isn't always a `next.config.js` file. 
It's more reliable to look at the package.json dependencies object for a next key. 
Fixes #260

Cli: improve Next.js project detection

---

.changeset/long-carrots-camp.md
packages/cli/src/commands/init.ts
packages/cli/src/utils/getUserPkgManager.ts

If the endpoint slug isn't passed in or in the package.json file, it will use the project slug.
If the next.config file doesn't exist, it works
There was an issue where the package artifact detection threw an error and it wasn't properly caught because it wasn't being awaited.

CLI init fixes: don't ask for endpoint slug, fix for next.config and package manager artifact issue

---

docs/documentation/guides/manual.mdx

related to https://github.com/triggerdotdev/trigger.dev/pull/286 
added the missing syntax highlight. currently its looking like this 
This PR will adds the syntax highlight to this section

Adds Missing syntax highlight to part of manual setup documentation

---

.changeset/three-flies-sneeze.md
packages/cli/src/commands/dev.ts

This PR addresses the issue where the `createTunnel` function fails to handle a specific ngrok error message that indicates the requirement for a `version` property in the configuration. The code has been refactored to handle this error message appropriately and perform the necessary configuration upgrade before retrying the tunnel creation.
- Refactored the `createTunnel` function to identify and handle the ngrok error message indicating the need for a `version` property in the configuration.
- Added logic to upgrade the ngrok configuration using the `ngrok config upgrade` command when the error message is detected.
- Improved error handling and logging to provide clear information about the configuration upgrade process and tunnel creation attempts.
1. Simulate the specific ngrok error …

fix: Handle ngrok config upgrade error in createTunnel function

---

.changeset/smooth-dodos-obey.md
packages/express/src/index.ts

Fixes #306 by properly creating an exception handler for the middleware code that would otherwise cause the Node.js process to crash.
The new error handler will forward the error thrown to the next middleware until an error handling takes place in the Express app and is the responsibility of the user to define and handle it as they choose to.

fix: avoid crashing the Node.js app on uncaught exceptions

---

.changeset/sixty-windows-run.md
packages/express/src/index.ts

Fixes #308 to support both scenarios in which:
1. Express makes use of a body parser middleware such as `express.json()` or `bodyParser.json()` (see references [here](https://expressjs.com/en/resources/middleware/body-parser.html) in official Express docs)
2. Express app doesn't explicitly use a body parser and the request parsing falls back to a readable stream passed to the underlying fetch implementation

fix: support express jsonParser middleware if used in the Express app

---

CONTRIBUTING.md

#While going through the Contribution.md file I found incorrect URL for cloning the project on a Windows machine
#318

Corrected clone link for Windows

---

docs/documentation/concepts/integrations.mdx

The first sentence in this paragraph for `### API Keys and Tokens` was missing a word or two and it wasn't entirely clear what did the original author of this docs page intended.
I've entered what seems to be the missing context but happy to re-phrase too if another wording makes better sense here.

docs: Update integrations.mdx

---

.changeset/fair-spiders-brake.md
packages/core/src/schemas/runs.ts

When getting an individual run (using hooks or `client.getRun()`) the types now include subtasks.

Add subtasks to the schema/types when getting an individual run

---

apps/webapp/app/utils.ts
packages/cli/src/utils/fileSystem.ts

This PR fixes:
1. Potentially undesired behavior that isn't consistent with isNaN (the global) vs Number.isNaN which is more strict
2. Node.js's own APIs that expects 'utf8' as an encoding argument value (rather than 'utf-8'. See https://nodejs.org/api/fs.html#filehandlereadfileoptions as an example)

fix: code quality nitpicks for some issues spotted

---

apps/webapp/app/entry.server.tsx

HTTP 1.1 spec defaults to ISO-8859-1 as a charset but likely we want to to set it to UTF-8.
Being explicit with character encoding.

fix: explicitly set a charset for rendered HTML documents

---

apps/webapp/app/components/run/RunOverview.tsx

Small code clean up (on the borderline of nitpick so we can dismiss if not up to your taste).
This change proposes handling the same case for 'default' and 'completed'. I figured it'd be easier on the eye this way rather than to create a new variable and re-use it.

fix: avoid code duplication by repostioning the default switch case

---

.changeset/rude-spoons-compete.md
packages/cli/src/commands/init.ts

fixes #373 
- I tested that the bug exists and also tested that the fix works.

bugfix: jsx extensions breaks cli init

---

apps/webapp/app/platform/zodWorker.server.ts
apps/webapp/app/routes/api.v1.events.$eventId.cancel.ts
apps/webapp/app/services/events/cancelEvent.server.ts
apps/webapp/app/services/events/ingestSendEvent.server.ts
packages/database/prisma/migrations/20230814131639_added_cancelled_at_column_to_the_event_record_table/migration.sql
packages/database/prisma/schema.prisma
packages/trigger-sdk/src/apiClient.ts
packages/trigger-sdk/src/io.ts
packages/trigger-sdk/src/triggerClient.ts

Added a function to cancel scheduled Events based on their ID. 
- added an API endpoint `api.v1.events.$eventId.cancel.ts` to update the cancelledAt column in the EventRecord table to the time the event was cancelled. 
- add a dequeue public function in the Zodworker class that handles removal of already scheduled jobs by calling the `graphile_worker.remove_job` SQL to remove the job.  
- Added a sendEvent function in the API Client class. 
fixes #230 
/claim #230

feat: added the ability to cancel scheduled Events based on the event ID

---

.changeset/calm-crabs-kick.md
.changeset/honest-dingos-tap.md
apps/webapp/app/services/endpoints/indexEndpoint.server.ts
apps/webapp/app/services/jobs/disableJob.server.ts
apps/webapp/app/services/jobs/registerJob.server.ts
apps/webapp/app/services/schedules/disableScheduleSource.server.ts
apps/webapp/app/services/schedules/nextScheduledEvent.server.ts
apps/webapp/app/services/schedules/registerScheduleSource.server.ts
apps/webapp/app/services/schedules/unregisterSchedule.server.ts
docs/documentation/guides/cli.mdx
examples/job-catalog/package.json
examples/job-catalog/src/events.ts
examples/job-catalog/src/schedules.ts
examples/job-catalog/src/stripe.ts
packages/cli/src/cli/index.ts
packages/cli/src/commands/dev.ts
packages/cli/src/commands/sendEvent.ts
packages/cli/src/commands/whoami.ts
packages/cli/src/utils/getTriggerApiDetails.ts
packages/cli/src/utils/triggerApi.ts
packages/database/prisma/migrations/20230822130655_add_status_to_job_version/migration.sql
packages/database/prisma/schema.prisma
packages/trigger-sdk/src/job.ts
packages/trigger-sdk/src/triggerClient.ts
pnpm-lock.yaml

This PR implements proper job disabling when the `enabled` option is set the `false`. Previously it just did not include the job when indexing.
When a job is set to enabled = false, the following things happen when the endpoint is indexed:
- The JobVersion.status field is set to `"DISABLED"`
- The EventDispatcher.enabled field is set to `false`. This will cause new runs from being created.
- If the job has a ScheduleSource, it will be deactivated and the next scheduled `events.deliverScheduled` task will be dequeued.
- In progress runs will continue to run, and new tasks from those runs will work.
- Resuming runs will not be allowed
- Any in-progress task operations will complete
When a job is then set backed to enabled = true, the following things happen when the endpoint is indexed:
- …

Implement the disable job feature backend when indexing endpoints

---

.changeset/nervous-masks-rest.md
packages/react/src/events.ts

closes #385 
Tested that undefined can now be accepted as an argument for useEventRunDetails in the nextjs-example folder. `useEventRunDetails(undefined)`

chore: updated the type in the eventId argument

---

.changeset/lovely-beers-collect.md
packages/cli/src/commands/dev.ts

fixes #403 
@matt-aitken I'm open to better ways of handling this, would love your thoughts on this.

fix: CLI dev command doesn't work if you're already running ngrok

---

.changeset/soft-hounds-clap.md
packages/cli/src/commands/dev.ts

This PR adds update checker for CLI's dev command
/claim #167

feat: Add update checker for CLI

---

apps/webapp/package.json
docker/scripts/entrypoint.sh

When using docker-compose to deploy to any remote environment, the same problem as #186 occurs.
This is caused by the following factors happening at the same time:
1. the `Secure` attribute exception does not work because the domain is not `localhost` (or browsers that respect the `Secure` attribute even on `localhost`, such as safari).
1. `NODE_ENV` is fixed to `production` and `Secure: NODE_ENV === "production"` is always `true`.
It can be reproduced in the local environment by replacing `http://localhost` with `http://127.0.0.1.nip.io`.
This pull request solves factor 2. of the above factors.
Therefore, it is assumed that #186 will be resolved in many cases.
When booted from a docker image, `entrypoint` calls `/docker/scripts/entrypoint.sh`,
Inside it, `exec dumb-init pnpm run start` …

Fix: Magic link login not working properly when booted from docker

---

docs/sdk/crontrigger.mdx

Fixes link in docs to the correct page. Currently goes to a 404 when clicking "Job's trigger" link, seen here: https://trigger.dev/docs/sdk/crontrigger

docs: crontrigger.mdx fix link to /docs/sdk/job

---

CONTRIBUTING.md

I have replaced the following:
```
git clone https://github.com/triggerdotdev/trigger.dev.git
```
with
```
git clone https://github.com/<github_username>/trigger.dev.git
```
This change has been made to avoid confusion when someone tries to fork and clone the repository locally

Documentation Update: Added <github_username> instead of triggerdotdev to avoid confusion while cloning the repository

---

docs/documentation/quickstarts/supabase.mdx

Fixes #489
Looks fine during dev even with (wrong) relative paths, but this should sort it.

Use absolute image paths

---

.changeset/three-worms-impress.md
integrations/stripe/src/index.ts
integrations/stripe/src/schemas.ts

Closes #426
---
Ran custom Stripe examples in `job-catalog` to test failures and passes.
---
- Added schemas and types
- Parsed schemas before creating triggers
---
```ts
// trying to use invalid event names like this.. 
stripe.onPrice({
// @ts-ignore
events: ["price.created", "price.updated", "test.abc"],
}
// ...now produces descriptive errors without sending data anywhere
{
received: 'test.abc',
code: 'invalid_enum_value',
options: [Array],
path: [Array],
message: "Invalid enum value. Expected 'price.created' | 'price.updated' | 'price.deleted', received 'test.abc'"
}
```
💯

fix: Fail client-side on invalid Stripe event names

---

.changeset/strong-seas-impress.md
apps/webapp/app/components/jobs/JobsTable.tsx
apps/webapp/app/components/run/RunCompletedDetail.tsx
apps/webapp/app/components/runs/RunStatuses.tsx
apps/webapp/app/services/runs/performRunExecutionV1.server.ts
apps/webapp/app/services/runs/performRunExecutionV2.server.ts
packages/core/src/schemas/api.ts
packages/core/src/schemas/errors.ts
packages/core/src/schemas/runs.ts
packages/database/prisma/migrations/20230922205611_add_invalid_payload_run_status/migration.sql
packages/database/prisma/schema.prisma
packages/trigger-sdk/package.json
packages/trigger-sdk/src/errors.ts
packages/trigger-sdk/src/triggerClient.ts
packages/trigger-sdk/src/triggers/eventTrigger.ts
packages/trigger-sdk/src/triggers/externalSource.ts
packages/trigger-sdk/src/types.ts
packages/trigger-sdk/src/utils/formatSchemaErrors.ts
pnpm-lock.yaml
references/job-catalog/package.json
references/job-catalog/src/events.ts

Zod Schemas is no longer required for validating/inferring event triggers. We’ve taken inspiration from how domain-functions did it: https://github.com/seasonedcc/domain-functions/pull/114
This also introduces a new run state called "Invalid Payload" when a Zod or other schema fails to successfully parse the event payload. Currently it just silently fails with no feedback.
Closes #487 
---
I ran some of the reference jobs in references/job-catalog/src/events.ts and made sure the new Invalid Payload error worked and made sure the types worked on Zod 3.21.4 and Zod 3.22.2
---
- See above
---
💯

fix: Decouple zod from `eventTrigger`

---

.changeset/perfect-poems-reply.md
apps/webapp/app/components/SetupCommands.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.setup.astro/route.tsx
docs/documentation/quickstarts/astro.mdx
docs/documentation/quickstarts/remix.mdx
packages/cli/src/frameworks/astro/astro.test.ts
packages/cli/src/frameworks/astro/index.ts
packages/cli/src/frameworks/index.ts
packages/cli/src/frameworks/nextjs/index.ts
packages/cli/src/frameworks/nextjs/nextjs.test.ts
packages/cli/src/templates/astro/apiRoute.js
packages/cli/src/templates/astro/exampleJob.js
packages/cli/src/templates/astro/jobsIndex.js
packages/cli/src/templates/astro/trigger.js
packages/cli/src/utils/fileSystem.ts

- CLI init can now install in an Astro project
- Added new docs quickstart
- Added new onboarding to the web app
- Made the Next.js setup work with other next.config extensions and "next" devDependency

Astro CLI support

---

apps/webapp/app/components/frameworks/FrameworkSelector.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.setup.astro/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.setup.express/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.setup.nextjs/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.setup.remix/route.tsx

---
Simple markup change so ran it locally to test
---
Added logos for all the frameworks on the setup onboarding pages. They display if we don't support the framework, so now they show when you do.
💯

Display framework logos on the onboarding setup pages

---

.changeset/sour-jars-punch.md
integrations/linear/src/index.ts

The helper previously accepted all valid params _except_ filters. It will now accept entity-specific filters as it should.
_edit:_ Also fixed search function params.
Maybe we could adopt a params pattern that exactly mirrors that of the target SDK, e.g.:
```ts
function searchDocuments(
key: IntegrationTaskKey,
...params: Parameters<LinearClient["searchDocuments"]>
): LinearReturnType<DocumentSearchPayload> {
return this.runTask(
key,
async (client) => {
const payload = await client.searchDocuments(...params);
...
// Option #1
linear.searchDocuments("task-key", "search terms", { first: 5 })
// Option #2 - alternatively as single array param
linear.searchDocuments("task-key", ["search terms", { first: 5 }])
```
Would prevent having to create keys, particularly for non-object params. These …

Add typed filters to `Linear` getAll helper

---

docs/documentation/concepts/triggers/introduction.mdx
docs/documentation/guides/deployment.mdx
docs/documentation/guides/react-hooks.mdx
docs/documentation/guides/using-integrations.mdx
docs/documentation/introduction.mdx
docs/documentation/quickstarts/introduction.mdx
docs/integrations/apis/github.mdx
docs/integrations/apis/supabase/introduction.mdx
docs/integrations/create.mdx
docs/integrations/introduction.mdx
docs/sdk/dynamicschedule/overview.mdx
docs/sdk/dynamictrigger/overview.mdx
docs/sdk/introduction.mdx
docs/sdk/io/overview.mdx
docs/sdk/react/introduction.mdx
docs/sdk/triggerclient/overview.mdx

chore: update doc title for groups

---

.changeset/orange-falcons-smile.md
apps/webapp/app/presenters/ApiRunPresenter.server.ts
apps/webapp/app/routes/api.v1.runs.$runId.cancel.ts
apps/webapp/app/routes/api.v1.runs.$runId.ts
apps/webapp/app/services/runs/getRun.server.ts
packages/trigger-sdk/src/apiClient.ts
packages/trigger-sdk/src/triggerClient.ts

Closes #554
---
- Validated the SDK functionality
- Verified the job cancellation from SDK
- Verified the job cancellation from the Dashboard
---
- Introduced `api/v1/runs/$runId/cancel` endpoint.
- Added `cancelJob` function to SDK.
- Consolidated the Job Run fetch into a `GetRunService`. This will be used in both `GET api/v1/runs/$runId` and `POST api/v1/runs/$runId/cancel` API.
- The new `cancel-job` endpoint returns basic job-run information and does not accept any search parameters (as it does in the get-run API). I don't think it makes sense to accept search parameters in the `cancel` API. The intention is if the user wants additional information, they can use the `get-run` with the `runId`.
---
💯

feat: allow cancelling jobs from trigger-client sdk

---

docs/sdk/eventtrigger.mdx

chore: add example for eventTrigger() doc

---

.changeset/tidy-toys-turn.md
packages/cli/src/commands/dev.ts
packages/cli/src/utils/getTriggerApiDetails.ts
packages/cli/src/utils/readEnvVariables.ts

Closes #509
---
- Executed CLI dev command to confirm that it uses the injected environment variables
- Executed CLI dev command to confirm that it uses the env file fallback when the env-var is unavailable
---
- Add a generic function to read environment variables from process runtime and env-file for the provided framework. Here, the process runtime takes precedence when a variable is present in both sources.
- Use this function to read `TRIGGER_API_KEY` and `TRIGGER_API_URL`.
💯

feat: allow CLI dev to use injected environment variables

---

examples/job-catalog/src/openai.ts

Added function call example in openAI.
/claim #469 
/closes #469
Note: 
I can't able to test the changes because I don't have an active openAI key. I consumed all of my free quota 🥺🥺

feat: Added example for openAI function call

---

apps/webapp/app/services/runs/createRun.server.ts
packages/database/prisma/migrations/20231005064823_add_job_run_internal/migration.sql
packages/database/prisma/schema.prisma

Closes #557
---
- Verified the migration is applied and the column is added to `JobRun` table.
- Verified the new job runs are using the `internal` flag from `Job` table (I did this by manually updating the `internal` flag for one of the jobs).
---
- Add new column `internal` in `JobRun` table (defaults to `false`)
- Set `JobRun` internal flag based on the job's definition in the `createRun` API.
💯

feat: add internal flag to job-run table

---

.changeset/tiny-candles-type.md
packages/cli/src/commands/sendEvent.ts

Regression on #532 merge since the `getTriggerApiDetails` response structure has changed.
Older `envFile` response param wasn't used in `sendEvent.ts`, hence removed it.

(regression) fix: remove invalid envFile response field in sendEvent cmd

---

.changeset/sharp-lobsters-cross.md
apps/webapp/app/routes/api.v1.runs.$runId.tasks.ts
docs/sdk/io/runtask.mdx
integrations/resend/src/index.ts
packages/core/src/schemas/api.ts
references/job-catalog/src/resend.ts

This also improves the retrying behavior of the resend integration by skipping retrying certain client errors
Closes #583
---
I created a new job to recreate this issue in job-catalog/resend.ts
---
- Update the parsing logic on the server to allow task properties with falsy values
- Filter out properties that have falsy values before persisting
- Improve the resend integration by skipping retries for certain client errors
---
💯

Fixes #583 by filtering out properties with missing values

---

docker/docker-compose.yml
docker/pgadmin/servers.json

The DB password isn't pre-configured as it requires a rather unsightly workaround.
1. Start just like the DB: `pnpm run docker`
2. Access at http://localhost:5480
3. Email: `admin@example.com`
4. Password: `admin`
5. Select the Trigger.dev DB, enter and save password: `postgres`

Add pgAdmin to compose file

---

.changeset/cool-stingrays-invent.md
packages/cli/src/cli/index.ts
packages/cli/src/commands/update.ts

Closes #484 
---
- Verified that the update command accepts the version and uses it for dependency update.
- Verified that the updated command falls back to `latest` if the version is not provided.
---
- Allows CLI users to provide a version for trigger-dev package update.
💯

feat: allow CLI update to accept a version for trigger-dev package

---

apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.jobs.$jobParam.test/route.tsx
apps/webapp/app/services/jobs/registerJob.server.ts
apps/webapp/app/utils/icon.ts

@ericallam  Something I came across while working on #534.
1. The API does not support unsetting an icon because Prisma differentiates between a variable having an `undefined` value vs `null` value ([ref](https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined)). When the user wishes to unset the example icon and does not send a value, the server fails to update the DB since it sets the value as `undefined`.
2. When the user provides an invalid name for the `icon` property, an empty icon is displayed in the dashboard.
I created this PR to fix the above issues.
---
- Verified setting an icon.
- Verified unsetting icon.
- Verified re-setting the icon.
- Verified that a valid icon is used when provided in the example (both internal named-icons, and company-icons …

Event Trigger Example Payload: Fix unsetting icon, and Use fallback icon in case of invalid icon-name.

---

apps/webapp/app/components/primitives/Toast.tsx
apps/webapp/app/components/stories/ToastUI.stories.tsx
apps/webapp/package.json
pnpm-lock.yaml

Closes #555
Fixes #559 
---
- Created new stories for UIs and toasts
---
- Removes react-hot-toast based Toast
- Adds Sonner based toast
---
[![image](https://github.com/triggerdotdev/trigger.dev/assets/37960163/05923975-699f-4be7-9604-e72de55b7dee)](https://github.com/triggerdotdev/trigger.dev/assets/37960163/aacae2e4-915b-4c8c-93af-1378eb87c9d8)
💯

Feat: Replaicing react hot toast with  Sonner toasts

---

apps/webapp/app/services/events/ingestSendEvent.server.ts

Closes #604 
---
- Verified event creation and subsequent run.
- without deliverAt / deliverAfter.
- with deliverAt / deliverAfter.
- Verified event updation and subsequent run.
- without deliverAt / deliverAfter.
- with deliverAt / deliverAfter.
- Verified event doesn't get updated when it is within the threshold window.
---
- Implement event update for duplicate requests.
- Use a threshold window to determine if the update should proceed.
💯

feat: allow sendEvent to update an existing event

---

.changeset/rude-kids-joke.md
integrations/openai/src/chat.ts
integrations/openai/src/completions.ts
integrations/openai/src/edits.ts
integrations/openai/src/embeddings.ts
integrations/openai/src/files.ts
integrations/openai/src/fineTunes.ts
integrations/openai/src/images.ts
integrations/openai/src/index.ts
integrations/openai/src/types.ts
references/job-catalog/src/openai.ts

This commit introduces the ability to set custom base URLs, which allows for the use of different APIs such as Perplexity. It also ensures that any OpenAI-related task now includes an idempotency key when making requests. Works for background tasks as well.
---
I updated the openai.ts job reference and added a new job that tests using the Perplexity AI API using the OpenAI integration.
---
See above.
---
💯

Add custom baseURL and idempotency key support to OpenAI integration

---

.changeset/soft-ties-turn.md
apps/webapp/app/routes/api.v1.events.$eventId.cancel-runs.ts
apps/webapp/app/services/events/cancelRunsForEvent.server.ts
docs/mint.json
docs/sdk/triggerclient/instancemethods/cancel-runs-for-event.mdx
docs/sdk/triggerclient/overview.mdx
packages/core/src/schemas/events.ts
packages/trigger-sdk/src/apiClient.ts
packages/trigger-sdk/src/triggerClient.ts

Closes #565 
---
- Verified the job runs are cancelled (as long as they're in the expected status). I did this by ensuring `startRunService` does not enqueue a worker event to execute the job, so the job-run would remain in `QUEUED` status.
---
- Implemented `/api/v1/events/$eventId/cancel-run` API.
- Implemented `cancelRunsForEvent` function in TriggerClient SDK.
- Added docs for the new SDK function.
---
💯

feat: allow cancelling job runs for an event-id

---

.changeset/tricky-games-agree.md
packages/trigger-sdk/src/io.ts
packages/trigger-sdk/src/triggerClient.ts

Closes #582 
---
Verified throwing an Error object, string, and a custom object.
---
Set error message based on the type of Error.
---
💯

fix: set error message in runTask & executeJob

---

apps/webapp/app/components/environments/RegenerateApiKeyModal.tsx
apps/webapp/app/models/api-key.server.ts
apps/webapp/app/models/organization.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.environments/route.tsx
apps/webapp/app/routes/resources.environments.$environmentId.regenerate-api-key.tsx

Closes #639 
---
- Verified regenerating the API key for an environment. Ensured it affects only this environment, and the updated API keys are reflected in the Environments & API keys page.
- Verified the error cases when trying to re-generate the API keys.
---
- Implement `resources/environments/$environmentId/regenerate-api-key` API.
- Add `regenerate` button for each environment in the Environments & API keys page.
- Add a modal for user confirmation of API key regeneration.
---
https://github.com/triggerdotdev/trigger.dev/assets/132386067/07b5d7b9-9775-4392-b70e-8d34bf003019
💯

feat: implement API key regeneration

---

CODE_OF_CONDUCT.md

Incorporating a Code of Conduct in your GitHub repository is crucial for promoting an inclusive, respectful community. It establishes guidelines, minimizes conflicts, safeguards participants, and adheres to legal standards. Additionally, it demonstrates professionalism and aligns with GitHub's best practices, contributing to a welcoming and harmonious environment, which, in turn, enhances collaboration and the project's overall success.
---
---
---
💯

added a missing CODE OF CONDUCT file

---

docs/integrations/apis/resend-tasks.mdx
docs/integrations/apis/resend.mdx
docs/mint.json

Closes #661 
---
I locally deployed the Docs Website using Netlify and verified all the changes.
https://github.com/triggerdotdev/trigger.dev/assets/47860497/eebc64e7-20d8-4d51-9d21-5bee54c7ffd3
---
The Resend Documentation has been updated such that it follows the same format as the GitHub Integration.
Resend Documentation is now divided into two sections.
- Resend Overview and Authentication
- Resend tasks
---

[TRI-1426] : Improve the Resend integration documentation

---

docs/documentation/guides/self-hosting/supabase.mdx

Closes #693 
Working as per issue report.

Fix: Set `NODE_ENV=production` in Supabase self-hosting docs

---

.changeset/silent-snails-float.md
integrations/airtable/src/base.ts
integrations/airtable/src/types.ts
references/job-catalog/src/airtable.ts

Closes #645 
We may have to extend this further in the future. See https://github.com/Airtable/airtable.js/issues/389 and the proposed fix for even more types.
---
Added a formula job to the Airtable entry in the `job-catalog`.
To test:
1. Create the fields as specified by the Formulas type.
2. Cause errors and special values by dividing by zero, leaving both number fields empty, etc.
---
- Extended the field set type by formula errors and special values
- Extended the `job-catalog` entry with a formula example
💯

Fix: Allow errors and special values on Airtable field set

---

apps/webapp/app/presenters/TestJobPresenter.server.ts

Closes #710
---
- Verified that the environment shows only the current user's `dev` environment.
- Verified that the triggered test-run is associated with the current user's `dev` environment.
---
Filter the current user's dev environment when fetching job info in the `TestJobPresenter`.
---
**Before**
<br>
**After**
<br>
💯

fix: show only the current user's dev env in run-test page

---

.env.example
apps/webapp/app/env.server.ts
apps/webapp/app/models/user.server.ts
apps/webapp/app/routes/magic.tsx
apps/webapp/app/utils/regex.ts

Closes #685 
---
1. Set `WHITELISTED_EMAILS` in .env with a regex with allowed emails.
2. Start the webapp with the command `pnpm run dev --filter webapp`.
3. Trying to log in with an unauthorized email should show an error.
4. Trying to log in with an authorized email should log in or create the account.
---
User can now set a WHITELISTED_EMAILS environment variable that must be a valid Regex to list the authorized emails.
---
💯

FIX: [TRI-1444] Allow only logins from WHITELISTED_EMAILS fixes #685

---

.changeset/mighty-dodos-study.md
docs/integrations/apis/resend.mdx
integrations/resend/package.json
integrations/resend/src/batch.ts
integrations/resend/src/emails.ts
integrations/resend/src/index.ts
integrations/resend/src/utils.ts
pnpm-lock.yaml
references/job-catalog/src/resend.ts

---
Added additional usages of Resend to the job reference file, as well as tested the deprecated API
---
- Upgrade resend integration package to use the [v2.0.0](https://github.com/resendlabs/resend-node/releases/tag/v2.0.0) resend SDK
- Fixes an issue where `@trigger.dev/resend` wasn't usable on Next.js 14
- Added batch APIs
- Added `emails.get`
- Adopt the "fluent" interface style of the SDK, and deprecate `io.resend.sendEmail`

Upgrade resend integration to use resend-node 2.0.0

---

apps/webapp/app/services/dispatchers/invokeEphemeralEventDispatcher.server.ts

@whatwg-node/fetch wasn't working when deployed. Now we're using plain old fetch

Fix for waitForEvent (switched to using fetch)

---

.changeset/yellow-kids-trade.md
apps/webapp/app/services/endpointApi.server.ts
apps/webapp/app/services/runs/deliverRunSubscription.server.ts
apps/webapp/app/services/runs/performRunExecutionV3.server.ts
docs/_snippets/jobs/options.mdx
docs/mint.json
docs/sdk/job.mdx
docs/sdk/run-notification.mdx
docs/sdk/triggerclient/instancemethods/define-job.mdx
docs/sdk/triggerclient/instancemethods/on.mdx
docs/sdk/triggerclient/overview.mdx
packages/core/src/schemas/api.ts
packages/core/src/schemas/runs.ts
packages/database/prisma/migrations/20231116113235_add_unique_index_on_job_run_sub/migration.sql
packages/database/prisma/schema.prisma
packages/trigger-sdk/package.json
packages/trigger-sdk/src/job.ts
packages/trigger-sdk/src/triggerClient.ts
packages/trigger-sdk/src/types.ts
pnpm-lock.yaml
references/job-catalog/package.json
references/job-catalog/src/notifications.ts

Related to #401 
---
Created a new notifications job reference file. Tested the following scenarios:
- A run succeeding with a client listener and a job listener
- A run failing with a client listener and a job listener
- Ensured that notification subscribers aren't created if the listeners are not active
---
Added support for run notification listeners on a single job:
```ts
client.defineJob({
id: "github-integration-on-issue",
name: "GitHub Integration - On Issue",
version: "0.1.0",
trigger: github.triggers.repo({
event: events.onIssue,
owner: "triggerdotdev",
repo: "empty",
}),
onSuccess: async (notification) => {
console.log("Job succeeded", notification);
},
onFailure: async (notification) => {
console.log("Job failed", notification);
},
run: async (payload, io, ctx) => {
await …
```

Add support for Run Notifications #401

---

integrations/shopify/tsup.config.ts
packages/core/src/schemas/api.ts

- The Shopify build was trying to use the new `@trigger.dev/tsup` package that hasn't been merged yet
- To support old SDKs, webhooks may now be undefined while indexing

Fix: Shopify build and webhook indexing

---

packages/core/src/requestFilterMatches.ts

Closes #759
This is a pre-requisite for https://github.com/triggerdotdev/api-reference/issues/108
---
Verified that the `headers` filter works on HTTP trigger.
---
Transform `Headers` object to `Record` type.
💯

fix: transform Headers object to Record type

---

apps/webapp/app/services/endpointApi.server.ts
apps/webapp/app/services/endpoints/performEndpointIndexService.ts
apps/webapp/package.json

Closes #786
---
Tested against a URL redirecting using a 308 on Vercel (root -> www) and made sure the endpoint URL was updated and the indexing completed successfully.
---
We will now detect redirects when doing an endpoint indexing request and update the endpoint URL to "follow" the redirect, and then retry the indexing. If that happens more than 5 times, we will abort. If the response is a redirect with no location URL, we will abort.

Auto update endpoint URL on redirect

---

.changeset/chilled-rivers-grab.md
packages/core/src/eventFilterMatches.ts
packages/core/src/schemas/eventFilter.ts
packages/core/test/eventFilterMatches.test.ts

Closes #810
---
- not filter added in event filters
---

feat: Add $not to eventFilters

---

docs/documentation/quickstarts/hono.mdx

using the `--env` cli flag requires fewer permissions (no need for env and fs access)

use --env cli flag for deno 

---

apps/webapp/app/components/event/EventDetail.tsx
apps/webapp/app/components/events/EventStatuses.tsx
apps/webapp/app/components/events/EventsFilters.tsx
apps/webapp/app/components/events/EventsTable.tsx
apps/webapp/app/components/navigation/SideMenu.tsx
apps/webapp/app/presenters/EventListPresenter.server.ts
apps/webapp/app/presenters/EventPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.events.$eventParam/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.events._index/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.events/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.jobs.$jobParam._index/ListPagination.tsx
apps/webapp/app/utils/pathBuilder.ts

Closes #818 
---
Add events list and event details page
---
[events.webm](https://github.com/triggerdotdev/trigger.dev/assets/82360525/64d2d94a-16ac-4ade-b224-6f582dc8296d)
💯

feat: Events list page

---

.changeset/shy-needles-push.md
integrations/stripe/src/index.ts

The SubtleCryptoProvider cannot be used in a synchronous context. This is a problem for non-node environments where the Stripe client falls back to SubtleCryptoProvider.
Running the trigger.dev Stripe integration on Cloudflare Pages results in the following error:
```
{
"error": {
"name": "Error",
"message": "SubtleCryptoProvider cannot be used in a synchronous context.\\nUse `await constructEventAsync(...)` instead of `constructEvent(...)`"
},
"timestamp": "2024-01-11T19:44:47.237Z",
"name": "trigger.dev",
"message": "[@trigger.dev/stripe] Error while validating webhook signature",
"level": "error"
}
```
Even worse, without verbose logging enabled, this is just silently ignored and no event or job-run is triggered from trigger.dev
---
Fix Stripe integration webhook validation.
💯

fix: stripe webhook validation

---

apps/webapp/app/components/billing/FreePlanUsage.tsx
apps/webapp/app/components/billing/UpgradePrompt.tsx
apps/webapp/app/components/stories/FreePlanUsage.stories.tsx
apps/webapp/app/presenters/OrganizationsPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.billing._index/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.billing.plans/route.tsx
apps/webapp/app/routes/api.v1.jobs.$jobSlug.invoke.ts
apps/webapp/app/services/runs/createRun.server.ts
packages/database/prisma/migrations/20240116162443_added_organization_runs_enabled_column/migration.sql
packages/database/prisma/schema.prisma

Runs can be disabled for an organization, this will be used when free organizations on the cloud product are over their free runs allowance.
Also made some messages clearer when Orgs are over the free allowance, they were unclear of too hidden before so it could be confusing.

Ability to disable organization runs + more obvious if you're over the free limit

---

.changeset/plenty-snails-smile.md
packages/cli/src/commands/dev.ts

This fixes the issue that emits this log pattern when running the `@trigger.dev/cli dev` command:
```
Error: WebSocket was closed before the connection was established
at WebSocket.close (/Users/eric/code/triggerdotdev/package-tests/nextjs-auto-yield/node_modules/ws/lib/websocket.js:287:7)
at _ReconnectingWebSocket._disconnect (file:///Users/eric/code/triggerdotdev/package-tests/nextjs-auto-yield/node_modules/partysocket/dist/chunk-KQKM3KLR.mjs:378:16)
at _ReconnectingWebSocket._handleError (file:///Users/eric/code/triggerdotdev/package-tests/nextjs-auto-yield/node_modules/partysocket/dist/chunk-KQKM3KLR.mjs:410:10)
at _ReconnectingWebSocket._handleTimeout (file:///Users/eric/code/triggerdotdev/package-tests/nextjs-auto-yield/node_modules/partysocket/dist/chunk-KQKM3KLR.mjs:369:10)
at …
```

Fix yalt.dev connection timeouts by increasing timeout from 1s to 5s

---

apps/webapp/app/components/primitives/PageHeader.tsx

Fixes triggerdotdev/trigger.dev#858
---
1. Navigated to integration detail page and noted the Jobs item appears correctly now when its value is 0.
---
Change PageInfoPropertyComponent to do an explicit undefined check instead of a truthy/falsy comparison.
---
💯

fix: Address unintended type coercion in PageInfoPropertyComponent

---

apps/webapp/app/components/integrations/ConnectToOAuthForm.tsx
apps/webapp/app/components/integrations/UpdateOAuthForm.tsx
apps/webapp/app/components/primitives/Checkbox.tsx

Closes #856 
The value of the checkbox wasn't coming through because we'd set it to "disabled". I had assumed that the value came through still in the form data… but it doesn't. So now we set the checkbox to readonly instead, I modified the checkbox component so it behaves nicely and is styled properly too.
I have tested with custom OAuth clients.
Note that `CLOUD_ENV=development` should NOT be used by anyone self-hosting Trigger.dev. It controls a bunch of things specific to the cloud, including communication with some private services. We intentionally don't document this environment variable anywhere. If you don't have this set the form should behave correctly for you, and force you to add custom OAuth clients each time.

Fix custom oauth client

---

.changeset/orange-eggs-fold.md
apps/webapp/app/routes/api.v2.events.$eventId.ts
apps/webapp/app/routes/api.v2.runs.$runId.statuses.ts
apps/webapp/app/routes/api.v2.runs.$runId.ts
packages/react/src/events.ts
packages/react/src/runs.ts
packages/react/src/statuses.ts
packages/trigger-sdk/src/apiClient.ts
references/nextjs-reference/package.json
references/nextjs-reference/src/jobs/hooks.ts

Closes #870 
Created new v2 API endpoints that return the full run status
- /api/v2/events/$eventId
- /api/v2/runs/$runId
- /api/v2/runs/$runId/statuses
They are an exact copy of v1 except they don't use the `runOriginalStatus` function which was created to fix a backwards compatibility bug.
The sdk and react packages have updated API urls to match these new endpoints.

Fix api run statuses

---

apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.environments/ConfigureEndpointSheet.tsx
apps/webapp/app/routes/resources.environments.$environmentParam.endpoint.$endpointParam.ts
apps/webapp/app/services/endpoints/deleteEndpointService.ts

Closes #551 
Added a "Delete" button in the top-right of the Endpoint sheet. Clicking it deletes the endpoint and closes the panel.

You can now delete an endpoint

---

apps/webapp/app/components/run/RunOverview.tsx
apps/webapp/app/presenters/EnvironmentsPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.environments/ConfigureEndpointSheet.tsx
apps/webapp/app/routes/resources.runs.$runId.rerun.ts
apps/webapp/app/services/endpoints/deleteEndpointService.ts
apps/webapp/app/services/endpoints/performEndpointIndexService.ts
apps/webapp/app/services/endpoints/probeEndpoint.server.ts
apps/webapp/app/services/endpoints/recurringEndpointIndex.server.ts
apps/webapp/app/services/httpendpoint/HandleHttpEndpointService.ts
apps/webapp/app/services/runs/createRun.server.ts
apps/webapp/app/services/runs/deliverRunSubscription.server.ts
apps/webapp/app/services/runs/performRunExecutionV3.server.ts
apps/webapp/app/services/sources/deliverHttpSourceRequest.server.ts
apps/webapp/app/services/sources/deliverWebhookRequest.server.ts
apps/webapp/app/services/triggers/initializeTrigger.server.ts
packages/database/prisma/migrations/20240129140944_endpoint_deleted_at_column/migration.sql
packages/database/prisma/migrations/20240129161848_endpoint_nullable_slug_instead_of_deletedat_column/migration.sql
packages/database/prisma/schema.prisma

Hard deleting endpoints has quite a few bad side effects:
- It deletes all associated runs
- It deletes all associated webhooks
- It deletes other assets that are associated
This PR changes the behaviour so "deleting" an endpoint actually just sets the URL to null. Most of the changes were to guard against a null URL and not continue.

Set endpoint URLs to null, instead of deleting them

---

apps/webapp/app/components/runs/RunsTable.tsx
apps/webapp/app/presenters/JobListPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.jobs.$jobParam._index/ListPagination.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.runs/route.tsx
packages/database/prisma/migrations/20240130165343_add_composite_index_to_job_run_for_job_id_and_created_at/migration.sql

The Jobs page was slow to load because getting the last run for each job was very slow.
Prisma was doing a weird query where it was returning all of the runs for a project, and then in code it was getting the latest one for each job. The query took about 1 second but then the code took a very long time for organizations with millions of runs.
The new query only gets the latest run for each org, then does the join in code.
I've also added a composite index to make getting the latest run faster. Plus use defer on the runs page.

Faster jobs page

---

apps/webapp/app/components/navigation/SideMenu.tsx
apps/webapp/app/models/runtimeEnvironment.server.ts
apps/webapp/app/presenters/OrganizationsPresenter.server.ts
apps/webapp/app/presenters/ProjectPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.settings/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug_.projects.new/route.tsx
apps/webapp/app/routes/resources.environments.$environmentParam.endpoint.$endpointParam.ts
apps/webapp/app/services/currentProject.server.ts
apps/webapp/app/services/deleteProject.server.ts
apps/webapp/app/services/endpoints/deleteEndpointService.ts
apps/webapp/app/services/jobs/deleteJob.server.ts
apps/webapp/app/utils/pathBuilder.ts
packages/database/prisma/migrations/20240131105237_project_deleted_at/migration.sql
packages/database/prisma/migrations/20240202115155_added_job_run_index_back_in_using_prisma_schema/migration.sql
packages/database/prisma/schema.prisma

Closes #638
Sidebar changes
- The title in the dropdown is the project name
- The section title above the project is just "Project"
- The section title above the organization is just "Organization"
- Added "Project settings" link
Project settings
- Rename project
- Delete project
Deleting a project
- Disables all endpoints by setting the URL to null
- Disables and soft-deletes all jobs
- Disables any linked schedules for the jobs
- Marks the project as deleted
- Clears the projectId from the session

Rename and delete projects

---

apps/webapp/app/components/navigation/SideMenu.tsx
apps/webapp/app/models/member.server.ts
apps/webapp/app/presenters/OrganizationsPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.settings/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.settings/route.tsx
apps/webapp/app/routes/account._index/route.tsx
apps/webapp/app/routes/unsubscribe.$userId.$token.tsx
apps/webapp/app/services/deleteOrganization.server.ts
apps/webapp/app/services/externalApis/integrationAuthRepository.server.ts
apps/webapp/app/utils/pathBuilder.ts
packages/database/prisma/migrations/20240206112723_organization_deleted_at/migration.sql
packages/database/prisma/migrations/20240206133516_integration_connections_can_be_disabled/migration.sql
packages/database/prisma/schema.prisma

The Organization settings page allows you to
- Rename your Org
- Delete your org
Deleting your org will also delete all the associated projects and integrations. You can't delete a project that has an active subscription so you must unsubscribe and wait for the billing period to end first.
In this PR there is also an /unsubscribe URL that allows emails to offer one-click unsubscribe.

Organization renaming, deleting and one-click email unsubscribe

---

apps/webapp/app/components/navigation/SideMenu.tsx
apps/webapp/app/presenters/NewOrganizationPresenter.server.ts
apps/webapp/app/presenters/SelectBestProjectPresenter.server.ts
apps/webapp/app/routes/_app.orgs.new/route.tsx
apps/webapp/app/services/deleteOrganization.server.ts
apps/webapp/app/services/deleteProject.server.ts

There were a few bugs with project/org deleting
- The code that selects the best project to show if there's no cookie and the user lands on the root of the site wasn't factoring in deleted projects
- If you delete your last project (across all orgs) an error was happening
- If an org had any deleted projects (ever) it couldn't be deleted
You could create multiple orgs and projects with the same name by hitting entering twice on the new org page

Fix edge cases with deleting last org/project

---

apps/webapp/app/presenters/JobListPresenter.server.ts

Multiple icons can get rendered in the Job list… I can't reproduce this locally but this PR deduplicates them in the presenter which hopefully will fix the problem.

Fix duplicated integration icons in the Jobs table

---

apps/webapp/app/components/runs/v3/SpanEvents.tsx
apps/webapp/app/components/runs/v3/SpanTitle.tsx
apps/webapp/app/presenters/v3/RunPresenter.server.ts
apps/webapp/app/presenters/v3/SpanPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam.spans.$spanParam/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam/route.tsx
apps/webapp/app/v3/authenticatedSocketConnection.server.ts
apps/webapp/app/v3/eventRepository.server.ts
apps/webapp/app/v3/marqs/devQueueConsumer.server.ts
apps/webapp/app/v3/services/cancelAttempt.server.ts
apps/webapp/app/v3/services/completeAttempt.server.ts
apps/webapp/app/v3/services/triggerTask.server.ts
packages/core/src/v3/index.ts
packages/core/src/v3/schemas/index.ts
packages/core/src/v3/schemas/openTelemetry.ts
packages/core/src/v3/utils/flattenAttributes.ts
packages/core/src/v3/utils/omit.ts
packages/database/prisma/migrations/20240227170811_add_is_cancelled_to_task_events/migration.sql
packages/database/prisma/schema.prisma

In progress runs will no auto-ack and be cancelled when the dev CLI exits (as to prevent runs to pollute future dev CLI sessions). This PR doesn't include the ability to cancel runs from the UI, which will come next.
Other things introduced in this PR:
- Spans can be "cancelled" and partial spans inherit their cancelled status/time from ancestors.
- "Task Run" spans are now partially created when runs are triggered, and completed/cancelled when the run is cancelled/completed

v3: Cancel dev runs when the dev CLI exits

---

apps/webapp/app/components/code/InlineCode.tsx
apps/webapp/app/components/primitives/Table.tsx
apps/webapp/app/components/runs/v3/TaskPath.tsx
apps/webapp/app/hooks/useLinkStatus.ts
apps/webapp/app/presenters/v3/TestPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.test/route.tsx
apps/webapp/app/utils/pathBuilder.ts
apps/webapp/app/utils/searchParams.ts
apps/webapp/package.json
pnpm-lock.yaml

The test UI has been reworked so you have to select an environment first.

Test page environment selection

---

apps/webapp/app/components/runs/v3/RunFilters.tsx
apps/webapp/app/components/runs/v3/TaskRunAttemptStatus.tsx
apps/webapp/app/components/runs/v3/TaskRunStatus.tsx
apps/webapp/app/components/runs/v3/TaskRunsTable.tsx
apps/webapp/app/presenters/v3/RunListPresenter.server.ts
apps/webapp/app/presenters/v3/TaskListPresenter.server.ts
apps/webapp/app/presenters/v3/TestTaskPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam._index/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam.spans.$spanParam/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.test.tasks.$taskParam/route.tsx

- The task list now shows the latest run using TaskRunStatus
- The run list uses the TaskRunStatus, and the status filters
- The test page uses the TaskRunStatus for recent payloads
Also made it so you can do 10x zoom on the span timeline
I created some new components for TaskRunStatus. We still have TaskRunAttemptStatus components which can be used.

Use TaskRunStatus (instead of TaskRunAttemptStatus)

---

apps/webapp/app/components/primitives/Table.tsx
apps/webapp/app/components/runs/v3/CancelRunDialog.tsx
apps/webapp/app/components/runs/v3/TaskRunsTable.tsx
apps/webapp/app/presenters/v3/RunListPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam.spans.$spanParam/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs._index/route.tsx
apps/webapp/app/v3/eventRepository.server.ts
apps/webapp/app/v3/services/cancelTaskRun.server.ts
packages/core/src/v3/index.ts
packages/core/src/v3/utils/flattenAttributes.ts

- If you click from a task to runs and there are none, guide you to the test page (or docs)
- You can cancel directly from the runs page
- The output of a task was screwed up if it was an object, it had $output as a prefix

Test, output and canceling improvements

---

packages/cli-v3/src/cli/common.ts
packages/cli-v3/src/cli/index.ts
packages/cli-v3/src/commands/deploy.ts
packages/cli-v3/src/commands/dev.tsx
packages/cli-v3/src/commands/init.ts
packages/cli-v3/src/commands/login.ts
packages/cli-v3/src/commands/logout.ts
packages/cli-v3/src/commands/whoami.ts
packages/cli-v3/src/utilities/configFiles.ts
packages/cli-v3/src/utilities/session.ts

You can now pass `--profile` to any of the v3 CLI commands to use that profile for auth in the CLI:
```sh
npx trigger.dev login --profile test
npx trigger.dev dev --profile test
npx trigger.dev deploy --profile test
```
If you don't pass a profile flag the `default` profile will be used.

v3: CLI profile support

---

docs/integrations/apis/openai/chat.mdx

---
---
Doc's code example for openai [`completions.backgroundCreate()`](https://trigger.dev/docs/integrations/apis/openai/chat#completions-backgroundcreate) was incorrectly using `completions.create()`
---

Fix opanai code example in docs

---

apps/webapp/app/components/runs/v3/SpanTitle.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam.spans.$spanParam/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam/route.tsx

- Text in the span title and code block now truncates
- Tree view toggle arrow doesn’t have red hover state if row is an error
https://github.com/triggerdotdev/trigger.dev/assets/7555566/6e4ec165-0617-4759-b32c-6ed4185d1c2a

Text truncation fixes

---

.changeset/cool-glasses-bake.md
.changeset/odd-poets-own.md
packages/cli-v3/src/cli/common.ts
packages/cli-v3/src/commands/dev.tsx
packages/cli-v3/src/templates/trigger.config.ts.template
packages/cli-v3/src/utilities/runtimeCheck.ts
packages/cli-v3/src/workers/dev/backgroundWorker.ts
packages/cli-v3/src/workers/dev/worker-facade.ts
packages/cli-v3/src/workers/prod/backgroundWorker.ts
packages/cli-v3/src/workers/prod/worker-facade.ts
packages/core/src/v3/index.ts
packages/core/src/v3/logger/taskLogger.ts
packages/core/src/v3/schemas/schemas.ts
packages/core/src/v3/types/config.ts
packages/trigger-sdk/src/v3/index.ts
references/v3-catalog/src/trigger/logging.ts
references/v3-catalog/trigger.config.ts

- Test runs automatically are set to TRIGGER_LOG_LEVEL=debug
- You can turn off logs using the `"none"` level
- This doesn't effect console.log/info/error/warn. Only the logger.debug/info.log methods

v3: implement configurable log levels via config file and env var

---

.changeset/mighty-camels-joke.md
.vscode/launch.json
packages/cli-v3/src/cli/common.ts
packages/cli-v3/src/commands/deploy.ts
packages/cli-v3/src/commands/dev.tsx
packages/cli-v3/src/utilities/deployErrors.ts
packages/cli-v3/src/utilities/installPackages.ts

v3: Better dev/deploy errors and handle image build errors

---

apps/webapp/app/env.server.ts
apps/webapp/app/routes/admin.api.v1.environments.$environmentId.ts
apps/webapp/app/v3/marqs.server.ts
apps/webapp/app/v3/marqs/devQueueConsumer.server.ts
apps/webapp/app/v3/marqs/index.server.ts
apps/webapp/app/v3/marqs/marqsKeyProducer.server.ts
apps/webapp/app/v3/marqs/priorityStrategy.server.ts
apps/webapp/app/v3/marqs/sharedQueueConsumer.server.ts
apps/webapp/app/v3/marqs/types.ts
apps/webapp/app/v3/marqsKeyProducer.server.ts
apps/webapp/app/v3/services/cancelAttempt.server.ts
apps/webapp/app/v3/services/cancelTaskRun.server.ts
apps/webapp/app/v3/services/completeAttempt.server.ts
apps/webapp/app/v3/services/createBackgroundWorker.server.ts
apps/webapp/app/v3/services/createCheckpoint.server.ts
apps/webapp/app/v3/services/createDeployedBackgroundWorker.server.ts
apps/webapp/app/v3/services/resumeAttempt.server.ts
apps/webapp/app/v3/services/resumeBatchRun.server.ts
apps/webapp/app/v3/services/resumeTaskDependency.server.ts
apps/webapp/app/v3/services/triggerTask.server.ts
apps/webapp/package.json
apps/webapp/test/marqs.test.ts
apps/webapp/tsconfig.json
apps/webapp/vitest.config.ts
packages/database/prisma/migrations/20240329142454_add_concurrency_limit_columns/migration.sql
packages/database/prisma/schema.prisma
pnpm-lock.yaml
references/v3-catalog/src/trigger/concurrency.ts

- It’s “queue choosing” algorithm is now MUCH better (pretty much didn’t work before) and should be performant even when we have a bunch of prod queues
- There are now concurrency limits at the environment and organization level, as well as the task/queue level. So if any of them are at capacity the message won’t be dequeued. This means we can have an org wide concurrency limit, as well as different limits for dev/prod/staging
- I’ve added an admin API that can be used to update the org/env concurrency limits
- Extract the queue priority choosing strategy into an interface
- Implement a much better weighted average strategy
- “Slide the window” of queue candidates if the parent queue sends all at-capacity queues (so we won’t get stuck attempting to choose the same 12 full queues)
- Added …

v3: Upgrades to MarQS

---

.changeset/breezy-gorillas-mate.md
.vscode/launch.json
apps/webapp/app/presenters/v3/DeploymentPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.deployments.$deploymentParam/route.tsx
apps/webapp/app/utils/json.ts
apps/webapp/app/v3/services/createBackgroundWorker.server.ts
packages/cli-v3/src/commands/deploy.ts
packages/cli-v3/src/commands/dev.tsx
packages/cli-v3/src/utilities/deployErrors.ts
packages/cli-v3/src/utilities/safeJsonParse.ts
packages/cli-v3/src/workers/common/errors.ts
packages/cli-v3/src/workers/dev/backgroundWorker.ts
packages/cli-v3/src/workers/dev/worker-facade.ts
packages/cli-v3/src/workers/prod/backgroundWorker.ts
packages/cli-v3/src/workers/prod/entry-point.ts
packages/cli-v3/src/workers/prod/worker-facade.ts
packages/core/src/v3/errors.ts
packages/core/src/v3/schemas/api.ts
packages/core/src/v3/schemas/messages.ts
packages/core/src/v3/zodIpc.ts
packages/core/src/v3/zodMessageHandler.ts

v3: better task metadata errors

---

apps/coordinator/src/index.ts
apps/webapp/app/env.server.ts
apps/webapp/app/v3/handleSocketIo.server.ts
apps/webapp/app/v3/marqs.server.ts
apps/webapp/app/v3/marqs/sharedQueueConsumer.server.ts
apps/webapp/app/v3/sharedSocketConnection.ts

This adds:
- Shared queue consumer pool with configurable size and intervals
- Configurable retry checkpoint threshold
- Improved tracing for marqs messages
- Some new (optional) env vars for the above

v3: shared queue pool

---

.changeset/spicy-lamps-smoke.md
packages/cli-v3/package.json
packages/cli-v3/src/commands/dev.tsx
packages/cli-v3/src/utilities/build.ts
packages/cli-v3/src/utilities/initialBanner.ts
packages/cli-v3/src/workers/dev/backgroundWorker.ts
pnpm-lock.yaml
references/v3-catalog/tsconfig.json

- Bundle `@trigger.dev/core` by resolving it's path through the `@trigger.dev/sdk`, because pnpm installs sub-dependencies in a nested format and `@trigger.dev/core` won't be found by node_module lookup
- Support `pnpx` & `pnpm dlx` by manually finding and adding the path to `node_modules/.pnpm/node_modules` to the `NODE_PATH` env var

v3: pnpm support

---

.changeset/light-dragons-complain.md
apps/kubernetes-provider/src/index.ts
packages/cli-v3/src/Containerfile.prod
packages/cli-v3/src/commands/deploy.ts
packages/cli-v3/src/workers/prod/backgroundWorker.ts
packages/cli-v3/src/workers/prod/entry-point.ts
pnpm-lock.yaml
references/v3-catalog/package.json
references/v3-catalog/src/trigger/binaries.ts

This adds:
- Better support for third party packages and binaries
- Write permissions for workdir
- Switch from alpine to bookworm-slim
- Small fix to final attempt shutdown

v3: prod image upgrade and fixes

---

.changeset/loud-actors-remember.md
packages/cli-v3/src/templates/trigger.config.ts.template

This changes the default `trigger.config.ts` setting for `retries.enabledInDev` to be true.

We want retrying enabled in dev by default, it’s confusing otherwise

---

.changeset/polite-ducks-switch.md
apps/kubernetes-provider/src/index.ts
packages/cli-v3/src/Containerfile.prod

Switch to busybox wget and only call start hook for restores, to reduce the impact of any future issues.

v3: fix start hook

---

apps/webapp/app/routes/api.v1.token.ts
apps/webapp/app/routes/api.v2.whoami.ts
apps/webapp/app/services/personalAccessToken.server.ts

You couldn't be logged in to the CLI on multiple machines at once. We have one token that is called "cli" and if you tried to create another it would delete the old one, effectively logging you out of your other machine.
- If you login to another CLI it will associate an existing "cli" token with the authorization code
- Improved the error messages from some of the endpoints (use "error" key and don't return 500s which appear as "Something went wrong".

Multiple machine CLI support

---

.changeset/angry-eagles-trade.md
docs/v3/trigger-config.mdx
packages/cli-v3/src/commands/deploy.ts
packages/cli-v3/src/utilities/deployErrors.ts
packages/cli-v3/src/utilities/links.ts
packages/core/src/v3/types/config.ts

Changelog:
- Fix additionalFiles that aren't decendants
- Stop swallowing uncaught exceptions in prod
- Improve warnings and errors, fail early on critical warnings
- New arg to --save-logs even for successful builds
Additional files that aren't decendants of the project dir were previously saved outside of the build context. They are now properly included like this:
- `../foo/bar` saved at `./foo/bar`
- `../../bar/baz` saved at `./bar/baz`
This means that a prisma schema in a monorepo can now be referenced like this:
trigger.config.ts
```ts
{
additionalFiles: ["../../packages/database/prisma/schema.prisma"]
}
```
package.json
```json
{
"scripts": {
"postinstall": "prisma generate --schema=./packages/database/prisma/schema.prisma"
}
}
```

v3: fix additionalFiles, uncaught exceptions, and improve errors

---

.changeset/rotten-beers-refuse.md
packages/cli-v3/src/Containerfile.prod

Previously, including private packages in the worker image caused errors because git wasn't installed. That's been fixed!
Example error:
`
npm WARN tarball tarball data for REPOSITORY@git+https://<PAT>x-oauth-basic@github.com/<USER>/<REPOSITORY> (null) seems to be corrupted. Trying again.
`

v3: fix private package installs

---

.changeset/rich-kangaroos-unite.md
apps/webapp/app/services/personalAccessToken.server.ts
packages/cli-v3/src/commands/login.ts
packages/cli-v3/src/commands/whoami.ts
packages/cli-v3/src/utilities/cliOutput.ts

The token would forever be stuck in the revoked state, so you could never login again. Even after confirming via the auth code page and getting a lovely "success" message. That's been fixed, and login command output was improved.

v3: fix for fresh CLI logins after CLI token revoke

---

.changeset/clever-carrots-travel.md
.changeset/mighty-flowers-train.md
docs/v3/tasks-overview.mdx
docs/v3/trigger-config.mdx
packages/cli-v3/package.json
packages/cli-v3/src/commands/deploy.ts
packages/cli-v3/src/commands/dev.tsx
packages/cli-v3/src/utilities/configFiles.ts
packages/core/src/v3/types/config.ts
packages/core/src/v3/types/index.ts
packages/core/src/v3/workers/taskExecutor.ts
packages/trigger-sdk/src/v3/shared.ts
pnpm-lock.yaml
references/v3-catalog/package.json
references/v3-catalog/src/handleError.ts
references/v3-catalog/src/trigger/decorators.ts
references/v3-catalog/src/trigger/orm/index.ts
references/v3-catalog/trigger.config.ts
references/v3-catalog/tsconfig.json

Adds support for `emitDecoratorMetadata: true` and `experimentalDecorators: true` in your tsconfig using the [`@anatine/esbuild-decorators`](https://github.com/anatine/esbuildnx/tree/main/packages/esbuild-decorators) package. This allows you to use libraries like TypeORM: 
```ts orm/index.ts
import "reflect-metadata";
import { DataSource } from "typeorm";
import { Entity, Column, PrimaryColumn } from "typeorm";
@Entity()
export class Photo {
@PrimaryColumn()
id!: number;
@Column()
name!: string;
@Column()
description!: string;
@Column()
filename!: string;
@Column()
views!: number;
@Column()
isPublished!: boolean;
}
export const AppDataSource = new DataSource({
type: "postgres",
host: "localhost",
port: 5432,
username: "postgres",
password: "postgres",
database: "v3-catalog",
entities: …
```

v3: Support decorators

---

docs/v3/errors-retrying.mdx

It wasn't obvious where `retry` is coming from, this adds an import line to the snippet.
---
Open the mintlify docs
---
---
💯

docs: add 'retry' import in code snippet

---

.changeset/blue-pumas-whisper.md
integrations/shopify/src/index.ts
integrations/shopify/src/webhooks.ts
references/job-catalog/src/shopify.ts

When initializing the Shopify Client with invalid parameters (excluding apiKey), errors are not explicitly thrown, resulting in a silent failure in the background. The user only sees an error message stating, "Error: Missing webhook ID for delete operation." This occurs because the current logic attempts to delete a webhook subscription first if its creation fails, possibly to avoid the "address already in use" exception. However, this logic is poorly documented, and only users running a trigger client with verbose mode enabled will see the debug message, "ERROR CREATING WEBHOOK RESTARTING WITH DELETE FIRST." In cases of invalid secret keys, this approach is ineffective and does not resolve the issue.
---
Localhost & Shopify Dev Store
---
- Added input validation for constructor …

Improvement: Added more context to Shopify webhook registering errors

---

apps/kubernetes-provider/src/index.ts
apps/kubernetes-provider/src/podCleaner.ts
apps/kubernetes-provider/src/taskMonitor.ts

This does two things:
- Deletes pods of completed runs every X seconds
- Deletes pods of failed runs every X * 2 seconds
X defaults to 300, i.e. 5 minutes. Failed run deletion is only a backup as the Task Monitor should already be dealing with this.

v3: automatic pod cleanup

---

apps/webapp/app/components/environments/EnvironmentLabel.tsx
apps/webapp/app/presenters/EnvironmentsPresenter.server.ts
apps/webapp/app/presenters/HttpEndpointPresenter.server.ts
apps/webapp/app/presenters/ProjectPresenter.server.ts
apps/webapp/app/presenters/v3/ApiKeysPresenter.server.ts
apps/webapp/app/presenters/v3/EnvironmentVariablesPresenter.server.ts
apps/webapp/app/presenters/v3/TaskListPresenter.server.ts
apps/webapp/app/presenters/v3/TestPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam._index/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.schedules.$scheduleParam/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.schedules/route.tsx
apps/webapp/app/utils/environmentSort.ts

If you had a large team then in some parts of the dashboard you'd see tons of environments next to each other.
Now it looks like this:
https://github.com/triggerdotdev/trigger.dev/assets/10635986/0b015f77-7ce0-4a6d-8e82-eb48180ee42f

Better display when there are lots of dev environment

---

apps/webapp/app/entry.server.tsx
apps/webapp/app/platform/zodWorker.server.ts
apps/webapp/app/services/db/graphileMigrationHelper.server.ts
apps/webapp/app/services/worker.server.ts
apps/webapp/package.json
pnpm-lock.yaml

Closes #396
1. Create this `docker-compose.yml`
```yaml
version: "3"
volumes:
db-data:
redis-data:
networks:
app_network:
external: false
x-env: &env
LOGIN_ORIGIN: http://localhost:3030
APP_ORIGIN: http://localhost:3030
PORT: 3030
REMIX_APP_PORT: 3030
MAGIC_LINK_SECRET: secret
SESSION_SECRET: secret
ENCRYPTION_KEY: ae13021afef0819c3a307ad487071c06
DATABASE_URL: &db-url postgresql://postgres:postgres@db:5432/postgres
DIRECT_URL: *db-url
GRACEFUL_SHUTDOWN_TIMEOUT: 5000
NODE_ENV: production
RUNTIME_PLATFORM: docker-compose
TRIGGER_LOG_LEVEL: debug
REDIS_HOST: redis
REDIS_PORT: 6379
REDIS_TLS_DISABLED: "true"
V3_ENABLED: "true"
services:
old-webapp:
image: &old-webapp ghcr.io/triggerdotdev/trigger.dev:main@sha256:d384445f6b279bec498d78ee11626aee164eeba07975cbdee8b3120f7e2efb8d
restart: "no" …
```

perf: migrate to graphile worker v0.16.6

---

apps/webapp/app/env.server.ts
apps/webapp/app/platform/zodWorker.server.ts
apps/webapp/app/routes/api.v1.endpoints.$environmentId.$endpointSlug.index.$indexHookIdentifier.ts
apps/webapp/app/services/apiRateLimit.server.ts
apps/webapp/app/services/endpoints/performEndpointIndexService.ts
apps/webapp/app/services/sources/handleHttpSource.server.ts
apps/webapp/app/services/worker.server.ts
apps/webapp/app/v3/tracer.server.ts

- Failed graphile jobs are no longer saved and cleaned up 7 days later, instead they are automatically deleted by *not* throwing in the run task
- Auto disable endpoints that have more than a day of failed indexes in a row
- No longer schedule webhooks to be delivered if an endpoint is disabled

v2: Graphile auto-cleanup and auto-endpoint disabling

---

apps/webapp/app/components/primitives/Dialog.tsx
apps/webapp/app/components/runs/v3/EnabledStatus.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.alerts.new/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.alerts/route.tsx

- Added environments labels
- Improved the icons for enabled/disabled
- Added Environments section with default selected and disabled options
- Added a tooltip to explain when you receive alerts
- Made the copy a bit friendlier and more obvious

More info about environments added to the alerts page and alerts modal

---

apps/webapp/app/components/environments/EnvironmentLabel.tsx
apps/webapp/app/models/orgIntegration.server.ts
apps/webapp/app/presenters/v3/ApiAlertChannelPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.alerts.new/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.alerts/route.tsx
apps/webapp/app/routes/api.v1.projects.$projectRef.alertChannels.ts
apps/webapp/app/v3/services/alerts/createAlertChannel.server.ts
apps/webapp/app/v3/services/alerts/deliverAlert.server.ts
apps/webapp/app/v3/services/alerts/performDeploymentAlerts.server.ts
apps/webapp/app/v3/services/alerts/performTaskAttemptAlerts.server.ts
packages/database/prisma/migrations/20240517105021_add_environment_types_to_alert_channel/migration.sql
packages/database/prisma/migrations/20240517105224_remove_test_alert_type/migration.sql
packages/database/prisma/schema.prisma

- We we're missing the `chat:write.public` scope which caused slack alerts to fail to post into public channels, unless the `@Trigger.dev` slack bot was explicitly invited to the channel.
- We'll need to add the `chat:write.public` scope to the list of bot scopes to our Slack apps @matt-aitken 
- There's currently no way for existing "OrganizationIntegrations" to re-authorize their slack connection to get the new scope, outside of them being deleted in the database and reconnected (we need to build a section of the dashboard for OrganizationIntegrations.
- We're now showing a much stronger warning message when selecting a private channel:

v3: Fix issues with posting alerts to public slack channels

---

apps/webapp/app/components/code/CodeBlock.tsx
apps/webapp/package.json
pnpm-lock.yaml

Prism React Renderer's latest version is compatible with Vite, so just updating here and fixing the one breaking change
---
---
---
💯

fix: upgrade prism react renderer

---

.changeset/cool-comics-burn.md
packages/cli-v3/src/commands/deploy.ts
packages/cli-v3/src/commands/dev.tsx
packages/cli-v3/src/workers/dev/backgroundWorker.ts
packages/cli-v3/src/workers/dev/worker-facade.ts
packages/cli-v3/src/workers/dev/worker-setup.ts
packages/cli-v3/src/workers/prod/worker-facade.ts
packages/cli-v3/src/workers/prod/worker-setup.ts
packages/core/src/v3/otel/tracingSDK.ts
pnpm-lock.yaml
references/v3-catalog/package.json
references/v3-catalog/src/telemetry.ts
references/v3-catalog/src/trigger/simple.ts

If a user has their own `@opentelemetry/api` package, which is a different version from ours, then task logs will fail to be sent to the platform because opentelemetry will fail to register our tracing API with the following error message:
```
Error: @opentelemetry/api: Registration of version v1.8.0 for trace does not match previously registered API v1.4.1
```
The solution was to make sure the user's `@opentelemetry/api` was not imported by the worker prior to our trace API registration. Removing the `@opentelemetry/resources` import from `worker-setup.ts` was enough to solve this problem because it imports `@opentelemetry/api`, and the top-level `@opentelemetry/api` inside node_modules is the users, not the one inside `@trigger.dev/core`.

Fix missing logs when client includes their own @opentelemetry/api

---

.changeset/hot-fishes-retire.md
packages/cli-v3/src/commands/init.ts

Closes #1017
---
1. Ensure that the `tsconfig.json` file does not contain an explicit `include` directive.
2. Run `pnpm exec triggerdev init`.
3. Verify if the `trigger.config.ts` file is not included in the `include` tsconfig directive.
4. Next, manually add an `include` directive to the `tsconfig.json` file.
5. Once the `include` directive is added, run  `pnpm exec triggerdev init` again.
6. Check if `trigger.config.ts` is included in the `include` directive tsconfig, as it should be based on the presence of the include directive.
---
This pull request addresses an issue specific to the `cli-v3 init` where TypeScript files were mistakenly included in the project directory when no include directive was present in `tsconfig.json`. Previously, the cli init added `trigger.config.ts` to the …

Fix TypeScript inclusion in tsconfig.json for `cli-v3 init`

---

apps/webapp/app/v3/services/triggerTask.server.ts
packages/database/prisma/migrations/20240523081426_added_task_run_number_counter_with_environment_as_well_as_task_identifier/migration.sql
packages/database/prisma/migrations/20240523082748_drop_old_task_run_counter_table/migration.sql
packages/database/prisma/schema.prisma

There was a bug where the task numbers were just looking at the taskIdentifier (the user-defined string in their tasks). This meant that if two tasks across different users had the same id (pretty likely) then the numbers wouldn't be correct.
This wasn't a security issue, it was purely used to increment the number for the TaskRun table. But obviously it's wrong so now the number is unique to the taskIdentifier + environmentId.

New TaskRunNumberCounter that uses taskIdentifier + environmentId

---

apps/webapp/app/models/runtimeEnvironment.server.ts
apps/webapp/app/presenters/ProjectPresenter.server.ts
apps/webapp/app/presenters/v3/EditSchedulePresenter.server.ts
apps/webapp/app/presenters/v3/EnvironmentVariablesPresenter.server.ts
apps/webapp/app/presenters/v3/RunListPresenter.server.ts
apps/webapp/app/presenters/v3/ScheduleListPresenter.server.ts
apps/webapp/app/presenters/v3/TaskListPresenter.server.ts
apps/webapp/app/presenters/v3/TestPresenter.server.ts
apps/webapp/app/presenters/v3/ViewSchedulePresenter.server.ts
apps/webapp/app/utils/environmentSort.ts

There some issues of varying seriousness when you delete a team member.
It showed multiple "Dev: you" tabs. This could result in test runs not working (if the first dev environment to be returned from the DB was a deleted one).
Fix was to remove all dev tabs that don't match your userId
It show extra "Dev: you" badges, one for each deleted user.
Fix was to remove those.
You saw extra runs that where marked as "Dev: you". 
Fix was to display them with "Dev: deleted".
It showed extra columns.
Fix: only show dev for your matching userId
It showed extra "Dev: you" badges/checkboxes.
Fix was to display them with "Dev: deleted".

Deal with Dev environments where the team member has been removed

---

apps/webapp/app/env.server.ts
apps/webapp/app/services/apiRateLimit.server.ts
apps/webapp/app/services/events/ingestSendEvent.server.ts
apps/webapp/app/services/rateLimiter.server.ts
apps/webapp/app/services/worker.server.ts
apps/webapp/package.json
pnpm-lock.yaml

- Updated to Upstash's newest ratelimit package
- Made it easy to create a rate limiter
- Switch the API rate limiter to use the new `RateLimiter` class
- Added a rate limiter to IngestSendEvent. It only queues the event if we're below the rate limit
We return undefined from IngestSendEvent `call()` if the rate limit has been hit. 
Practically this means:
- `DeliverScheduledEvent` will throw an error causing a retry (max is 8 attempts)
For all other uses it will fail to do the runs, and will always log this message:
> "IngestSendEvent: Rate limit exceeded"

v2 IngestSendEvent rate limit

---

.changeset/itchy-chairs-itch.md
apps/webapp/app/v3/marqs/index.server.ts
apps/webapp/app/v3/services/createBackgroundWorker.server.ts
apps/webapp/app/v3/services/triggerTask.server.ts
packages/trigger-sdk/src/v3/shared.ts
references/v3-catalog/package.json
references/v3-catalog/src/queues.ts

Closes #1137 
When calling trigger or batchTrigger (and their await variants) you can pass in a custom queue. This wasn't properly supported before.
This PR includes a test script (queues) that can be run in the v3-catalog.

Support custom queue when triggering a task

---

.changeset/young-snails-sell.md
apps/coordinator/src/backoff.ts
apps/coordinator/src/index.ts
apps/kubernetes-provider/src/index.ts
apps/webapp/app/env.server.ts
apps/webapp/app/v3/handleSocketIo.server.ts
apps/webapp/app/v3/services/initializeDeployment.server.ts
packages/cli-v3/src/workers/prod/backgroundWorker.ts

This will allow us to set a failover registry to use during maintenance. Deploys will use the failover, checkpoints will be retried until maintenance completes. If checkpoints fail even after backoff, the runs should still resume normally, but containers will stay up until they do.
Other changes:
- Improved logging of socket.io handler errors on webapp side
- Handle remaining coordinator errors, don't just log
- Increase cleanup IPC timeout (the only change that requires package release)

v3: registry maintenance

---

apps/webapp/app/services/events/deliverEvent.server.ts
apps/webapp/app/services/events/ingestSendEvent.server.ts
references/job-catalog/src/events.ts

If you have SQS setup it's possible that they deliver the same event multiple times. In this case it was possible that we triggered the same run again with the same event id.
There are two changes that prevent this
- `DeliverEventService` will fail if the event is already delivered, preventing any Graphile jobs from being enqueued.
- `IngestSendEvent` will return the original event and won't enqueue a Graphile job if the event is already delivered.

Fix for sendEvent same id causing multiple runs

---

.changeset/strong-phones-smoke.md
packages/cli-v3/src/commands/login.ts

I'm new to trigger.dev and want to start with v3. I was playing with the self-hosted version since i don't have access for v3  cloud version. 
During my setup, I noticed that the login command (triggered by deploy) does not respect the --api-url argument. To work around this, I have to set TRIGGER_API_URL in the GitHub Action step environment. However, this is not mentioned in the GitHub Action guide. https://trigger.dev/docs/v3/github-actions
This fix allows the login command to respect the --api-url argument.
---
---
allow login command to read api url from cli args
💯

fix: allow command login to read api url from cli args

---

.changeset/silly-buses-obey.md
apps/coordinator/src/index.ts
apps/webapp/app/presenters/v3/RunListPresenter.server.ts
apps/webapp/app/v3/handleSocketIo.server.ts
apps/webapp/app/v3/marqs/sharedQueueConsumer.server.ts
apps/webapp/app/v3/services/cancelAttempt.server.ts
apps/webapp/app/v3/services/cancelTaskRun.server.ts
apps/webapp/app/v3/services/crashTaskRun.server.ts
apps/webapp/app/v3/services/createCheckpoint.server.ts
apps/webapp/app/v3/services/restoreCheckpoint.server.ts
apps/webapp/app/v3/taskStatus.ts
packages/core/src/v3/schemas/messages.ts

This affects `Task.triggerAndWait()` and `Task.batchTriggerAndWait()`. A race condition could result where the dependency completes just before the checkpoint does.
If the timing is just right, the created checkpoint causes the resume message from dependency completion to be ACKed. This means the parent task stays stuck in the frozen state. Another issues is that even if the resume comes through, there's won't be a running task to send it to, as checkpoint completion also results in parent task termination.
The fix involves checking for dependency completion after creating the checkpoint event, and only ACKing if the dependency hasn't completed yet. Also, if the dependency has completed, we will keep the parent task alive so it can resume immediately.

v3: fix dependency checkpoint race

---

.changeset/sweet-ducks-remember.md
apps/webapp/app/v3/tracer.server.ts
docs/v3/triggering.mdx
packages/trigger-sdk/src/v3/runs.ts
packages/trigger-sdk/src/v3/schedules/index.ts
packages/trigger-sdk/src/v3/shared.ts
packages/trigger-sdk/src/v3/tasks.ts
pnpm-lock.yaml
references/v3-catalog/package.json
references/v3-catalog/src/clientUsage.ts
references/v3-catalog/src/trigger/simple.ts
references/v3-catalog/src/trigger/subtasks.ts

You can now trigger tasks in a typesafe way, without importing the task file at run time:
```ts Next.js API route
import { tasks } from "@trigger.dev/sdk/v3";
import type { emailSequence } from "~/trigger/emails";
//     👆 **type-only** import
//app/email/route.ts
export async function POST(request: Request) {
//get the JSON from the request
const data = await request.json();
// Pass the task type to `trigger()` as a generic argument, giving you full type checking
const handle = await tasks.trigger<typeof emailSequence>("email-sequence", {
to: data.email,
name: data.name,
});
//return a success response with the handle
return Response.json(handle);
}
```
You can also now use the `handle` returned from `tasks.trigger` or `myTask.trigger` to retrieve the output of a run in a typesafe …

v3: Adding SDK functions for triggering tasks in a typesafe way

---

.changeset/purple-spiders-care.md
.changeset/tall-masks-repeat.md
apps/kubernetes-provider/src/index.ts
apps/kubernetes-provider/src/taskMonitor.ts
apps/webapp/app/components/runs/v3/TaskRunsTable.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.schedules.$scheduleParam/route.tsx
apps/webapp/app/v3/services/crashTaskRun.server.ts
apps/webapp/app/v3/services/deploymentIndexFailed.server.ts
packages/cli-v3/src/commands/deploy.ts
packages/cli-v3/src/commands/dev.tsx
packages/cli-v3/src/utilities/getUserPackageManager.ts
packages/cli-v3/src/workers/common/errors.ts
packages/cli-v3/src/workers/prod/entry-point.ts
packages/core-apps/src/process.ts
packages/core-apps/src/provider.ts
packages/core/src/v3/schemas/messages.ts

There was an issue with file watchers possibly not being cleaned up after exiting the dev command. This can become an issue when running the command multiple times without rebooting your system. It's been fixed by making the cleanup function async and correctly awaiting the file watcher close step.
Also fixed:
- Artifact detection logs
- OOM detection and error messages
Small improvements:
- Next runs table for disabled schedules
- Test link for deployment completion message

v3: various small fixes

---

docs/v3/github-actions.mdx

- Correct typo.
- Add a link because I would've preferred this when reading the docs.

Add clarity to GitHub Actions doc

---

.changeset/curly-monkeys-tell.md
apps/webapp/app/v3/authenticatedSocketConnection.server.ts
apps/webapp/app/v3/services/heartbeatService.server.ts
apps/webapp/app/v3/sharedSocketConnection.ts
apps/webapp/app/v3/utils/zodPubSub.server.ts
packages/cli-v3/src/commands/dev.tsx
packages/cli-v3/src/workers/dev/backgroundWorker.ts
packages/core/src/v3/schemas/messages.ts
packages/core/src/v3/zodMessageHandler.ts

WebSockets could previously time out when no messages were sent for a period of 60s. This is due to load balancer connection timeouts. The only real fix here was to add a ping / pong mechanism that will keep connections alive during periods of rest, e.g. when waiting within or between attempts.
Pings will be automatically sent from the server every 45s. Clients will reply with pongs, but we just log those for now.
Whenever a dev CLI disconnects it will also cancel all in-progress dev runs. This shouldn't happen anymore.
This fix also prevents uncaught exceptions related to schema parsing.

v3: fix websocket timeouts

---

.changeset/thirty-hotels-raise.md
apps/webapp/app/components/runs/v3/ScheduleFilters.tsx
apps/webapp/app/components/runs/v3/ScheduleType.tsx
apps/webapp/app/components/runs/v3/TaskRunsTable.tsx
apps/webapp/app/presenters/v3/EditSchedulePresenter.server.ts
apps/webapp/app/presenters/v3/ScheduleListPresenter.server.ts
apps/webapp/app/presenters/v3/ViewSchedulePresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.schedules.$scheduleParam/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.schedules.edit.$scheduleParam/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.schedules/route.tsx
apps/webapp/app/routes/api.v1.projects.$projectRef.background-workers.ts
apps/webapp/app/routes/api.v1.schedules.$scheduleId.ts
apps/webapp/app/routes/api.v1.schedules.ts
apps/webapp/app/v3/services/checkSchedule.server.ts
apps/webapp/app/v3/services/createBackgroundWorker.server.ts
apps/webapp/app/v3/services/createDeployedBackgroundWorker.server.ts
apps/webapp/app/v3/services/deleteTaskSchedule.server.ts
apps/webapp/app/v3/services/setActiveOnTaskSchedule.server.ts
apps/webapp/app/v3/services/testTask.server.ts
apps/webapp/app/v3/services/triggerScheduledTask.server.ts
apps/webapp/app/v3/services/upsertTaskSchedule.server.ts
docs/v3-openapi.yaml
docs/v3/tasks-scheduled.mdx
packages/core/src/v3/schemas/api.ts
packages/core/src/v3/schemas/resources.ts
packages/core/src/v3/schemas/schemas.ts
packages/database/prisma/migrations/20240717101035_add_task_schedule_type_dynamic_and_static/migration.sql
packages/database/prisma/schema.prisma
packages/trigger-sdk/src/v3/schedules/index.ts
references/v3-catalog/src/trigger/scheduled.ts

This is for this roadmap feature: https://feedback.trigger.dev/p/static-cron-attached-to-tasks
We've called them "declarative" schedules as they're declared in your code on a task like this:
```ts
export const firstScheduledTask = schedules.task({
id: "first-scheduled-task",
//every two hours (UTC timezone)
cron: "0 */2 * * *",
run: async (payload, { ctx }) => {
//do something
},
});
```
Or you can specify a timezone if you don't want UTC:
```ts
export const secondScheduledTask = schedules.task({
id: "second-scheduled-task",
cron: {
//5am every day Tokyo time
pattern: "0 5 * * *",
timezone: "Asia/Tokyo",
},
run: async (payload) => {},
});
```
These schedules are synced when you run the `dev` or `deploy` CLI commands. If you create, edit or delete the cron property it will be reflected …

Declarative schedules

---

.changeset/young-jars-wait.md
.github/workflows/publish.yml
packages/cli-v3/e2e/fixtures/resolve-legacy-peer-deps/.npmrc
packages/cli-v3/e2e/fixtures/resolve-legacy-peer-deps/pnpm-lock.yaml
packages/cli-v3/e2e/index.test.ts

---
---
Fix  cli v3 e2e test suite various issues
---
💯

Fix cli v3 e2e suite issues

---

.changeset/brown-boats-bathe.md
apps/kubernetes-provider/src/index.ts
apps/kubernetes-provider/src/podCleaner.ts
apps/webapp/app/v3/services/createDeployedBackgroundWorker.server.ts
packages/core-apps/src/provider.ts
packages/core/src/v3/schemas/messages.ts

When deployments complete, this will pre-pull the image to all worker machines. Super cold starts should be a thing of the past.

v3: pre-pull deployments for faster startups from the first run

---

.changeset/few-poems-vanish.md
apps/webapp/app/v3/marqs/sharedQueueConsumer.server.ts
apps/webapp/app/v3/models/workerDeployment.server.ts
apps/webapp/app/v3/services/triggerTask.server.ts
packages/trigger-sdk/src/v3/shared.ts
references/v3-catalog/package.json

Custom queues defined at task creation will now be respected when triggering those tasks in different scenarios. This covers all envs, including the test page. Changes can be tested by running `pnpm queues` in the v3 catalog.

v3: fix triggering tasks with custom queues

---

apps/webapp/app/v3/failedTaskRun.server.ts
apps/webapp/app/v3/marqs/sharedQueueConsumer.server.ts
apps/webapp/app/v3/services/cancelAttempt.server.ts
apps/webapp/app/v3/services/cancelTaskRun.server.ts
apps/webapp/app/v3/services/completeAttempt.server.ts
apps/webapp/app/v3/services/crashTaskRun.server.ts
apps/webapp/app/v3/services/expireEnqueuedRun.server.ts
apps/webapp/prisma/populate.ts
packages/database/prisma/migrations/20240801175428_added_task_run_completed_at_column/migration.sql
packages/database/prisma/schema.prisma

Add TaskRun `completedAt` column in preparation for some changes that are coming. It gets set when a TaskRun is in one of the finished statuses. We have not done a migration that sets this column for existing runs because that operation would be too expensive when deploying.

Added TaskRun completedAt column

---

apps/webapp/app/components/navigation/SideMenu.tsx
apps/webapp/app/components/navigation/SideMenuItem.tsx
apps/webapp/app/components/primitives/Badge.tsx
apps/webapp/app/components/primitives/Popover.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug._index/route.tsx
apps/webapp/app/routes/storybook.badges/route.tsx

Added a Paid plan badge next to Billing in the side menu
Removed the v3 badge for v3 projects in the project menu. Added a v2 badge if you have a v2 project
New end-of-life messaging for if you're on a v2 project
The dropdown menu now reflects the UI design colours

V2 end of life messaging, paid plan badge, and project menu improvements

---

apps/webapp/app/components/navigation/SideMenu.tsx

v2 usage meter in side menu no longer displays when on a v2 paid plan

Fixed v2 usage meter displaying when on paid plan

---

apps/webapp/app/components/admin/debugTooltip.tsx
apps/webapp/app/components/navigation/SideMenu.tsx
apps/webapp/app/models/runtimeEnvironment.server.ts
apps/webapp/app/models/task.server.ts
apps/webapp/app/presenters/v3/ConcurrencyPresenter.server.ts
apps/webapp/app/presenters/v3/RunListPresenter.server.ts
apps/webapp/app/presenters/v3/TaskListPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.concurrency/route.tsx
apps/webapp/app/routes/admin.concurrency.tsx
apps/webapp/app/routes/admin.orgs.tsx
apps/webapp/app/routes/admin.tsx
apps/webapp/app/utils/pathBuilder.ts
apps/webapp/app/v3/marqs/index.server.ts
apps/webapp/app/v3/marqs/types.ts
apps/webapp/app/v3/services/enqueueDelayedRun.server.ts
apps/webapp/app/v3/services/executeTasksWaitingForDeploy.ts
apps/webapp/app/v3/services/resumeBatchRun.server.ts
apps/webapp/app/v3/services/resumeTaskDependency.server.ts
apps/webapp/app/v3/services/taskRunConcurrencyTracker.server.ts
apps/webapp/app/v3/services/triggerTask.server.ts
packages/database/prisma/migrations/20240809153150_background_worker_task_add_index_for_quick_lookup_of_task_identifiers/migration.sql
packages/database/prisma/schema.prisma
references/v3-catalog/src/trigger/performance.ts

In the current UI the Tasks page has a "Running" column. You would think this is the same as the amount of concurrency you have but it's not. It's the number of tasks that have actually started executing code which is different from the number that have been dequeued (and are just about to start executing). This difference can be extreme in the case of runs that do a very small amount of compute time.
This PR adds accurate tracking of actual concurrency. Any run that has been dequeued and not acked or nacked counts towards your concurrency. We track this using Redis by:
- Task
- Environment
- Globally for dev
- Globally for deployed
Additionally a new Concurrency page has been added that surfaces this data:

Concurrency page and more accurate tracking

---

apps/webapp/app/presenters/v3/ConcurrencyPresenter.server.ts
apps/webapp/app/presenters/v3/EditSchedulePresenter.server.ts
apps/webapp/app/presenters/v3/EnvironmentVariablesPresenter.server.ts

We were showing "Dev" environments for removed team members on:
- Environment variables page
- Environment variables create/edit page
- Concurrency limits
- Create/edit schedule

Fix: was showing deleted team member dev environments

---

apps/webapp/app/v3/marqs/index.server.ts
apps/webapp/app/v3/services/createCheckpoint.server.ts
apps/webapp/app/v3/services/resumeBatchRun.server.ts
apps/webapp/app/v3/services/resumeTaskDependency.server.ts
references/v3-catalog/src/trigger/checkpoints.ts

Heartbeats weren't being stopped when a checkpoint was created for `andWait`. They were for just `wait` because `marqs.replaceMessage` stops heartbeats.
I've added a specific call to stop heartbeats in these cases.
Additionally, the concurrency tracker (not used in logic, only for display purposes in the dashboard) was getting out of sync because some marqs payloads were missing required data.

Stop heartbeats when creating andWait checkpoints, fix for concurrency tracker

---

apps/webapp/app/routes/api.v1.projects.$projectRef.background-workers.ts
apps/webapp/app/v3/marqs/index.server.ts

It was possible in some edge cases for the concurrency to be taken by a run and the message to get enqueued again without the original concurrency being cleared. This causes problems if you're maxed out with your concurrency (at the org, environment, or task/queue level).
The change here remove the concurrency keys when enqueuing, since obviously it's not running if we're enqueuing.

When enqueuing clear concurrency for that run

---

.changeset/rotten-eggs-occur.md
docs/guides/new-build-system-preview.mdx
packages/build/package.json
packages/build/src/extensions/core/additionalPackages.ts
packages/build/src/extensions/index.ts
packages/build/src/extensions/prisma.ts
packages/build/src/extensions/typescript.ts
packages/cli-v3/src/commands/deploy.ts
packages/cli-v3/src/commands/dev.ts
packages/cli-v3/src/dev/workerRuntime.ts
packages/cli-v3/src/utilities/dotEnv.ts
packages/core/src/v3/build/extensions.ts
pnpm-lock.yaml
references/v3-catalog/package.json
references/v3-catalog/prisma/schema/schema.prisma
references/v3-catalog/src/kysely/types.ts
references/v3-catalog/trigger.config.ts

This PR adds support for adding custom esbuild plugins to the build through the `esbuildPlugin` build extension:
```ts
import { defineConfig } from "@trigger.dev/sdk/v3";
import { esbuildPlugin } from "@trigger.dev/build/extensions";
import { sentryEsbuildPlugin } from "@sentry/esbuild-plugin";
export default defineConfig({
project: "<project ref>",
build: {
extensions: [
esbuildPlugin(
sentryEsbuildPlugin({
org: process.env.SENTRY_ORG,
project: process.env.SENTRY_PROJECT,
authToken: process.env.SENTRY_AUTH_TOKEN,
}),
// optional - only runs during the deploy command, and adds the plugin to the end of the list of plugins
{ placement: "last", target: "deploy" }
),
],
},
});
```
If you have multiple `generator` statements defined in your schema file, you can pass in the `clientGenerator` …

Add support + docs for custom esbuild plugins

---

.changeset/fast-ladybugs-eat.md
apps/webapp/app/presenters/v3/SpanPresenter.server.ts
apps/webapp/app/v3/failedTaskRun.server.ts
apps/webapp/app/v3/marqs/index.server.ts
apps/webapp/app/v3/services/triggerTask.server.ts
packages/core/src/v3/workers/taskExecutor.ts
references/v3-catalog/src/trigger/checkpoints.ts

When using `triggerAndWait()` or `batchTriggerAndWait()` free up concurrency for the environment and org straight away. If it's a recursive task (i.e. the task calls itself again) then also free up the concurrency for the task queue.
This fixes some issues where at maximum concurrency it's possible for a run to get stuck. In production runs were clearing their concurrency after the heartbeats failed, but this slowed down execution by up to 2 mins.
When a run fails, we now ensure there is an error on the final attempt (if there isn't already one). There were some runs with "SYSTEM_FAILURE" but no information on why, except in the logs which is hard to dig out.
We were showing run errors even if attempts were still happening. This was confusing. Now we only show an error on the run if the …

Free up concurrency when using triggerAndWait. Improved errors on runs

---

docs/cli-deploy.mdx
docs/deploy-environment-variables.mdx
docs/triggering.mdx

- Triggering docs page now separated into 2 sections (triggering from your backend and from within a run)
- Deploy page now links to the GitHub actions page for CI setup
- New accordion in batchTriggerAndWait to explain how to handle errors
- Added new section for using google credential files in the deploy environment variables page

Docs improvements

---

.gitignore
apps/webapp/app/presenters/TeamPresenter.server.ts
apps/webapp/app/presenters/v3/AlertChannelListPresenter.server.ts
apps/webapp/app/presenters/v3/ScheduleListPresenter.server.ts
apps/webapp/app/v3/services/checkSchedule.server.ts
apps/webapp/app/v3/services/createCheckpoint.server.ts
apps/webapp/app/v3/services/initializeDeployment.server.ts
apps/webapp/app/v3/services/resumeTaskDependency.server.ts
references/v3-catalog/src/trigger/checkpoints.ts

It's possible that runs can get permanently frozen when at max concurrency (for your parent task or on your entire environment/org) when using batchTriggerAndWait.
This happens when the child run finishes before the checkpoint has completed.
Additionally a couple of unrelated fixes in this PR:
- Fix for doing remote image build when not self-hosting
- Set team members, alerts and schedule limits to 100m for self-hosting

batchTriggerAndWait checkpoint race condition when at max concurrency

---

apps/coordinator/src/index.ts

In some cases, expected checkpoint cancellations, e.g. when a dependency finishes before the parent checkpoint has been created, could cause the run to crash. This has been fixed by adding custom errors for all readiness interruptions. We now correctly distinguish between them and only crash on timeouts. If a run doesn't become ready to checkpoint within 20s, it's likely stuck forever and will be unable to resume in all scenarios.

Prevent crashes on expected checkpoint cancellations

---

apps/webapp/app/components/billing/v3/UsageBar.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.v3.usage/route.tsx

The predicted usage bar was confusing many people because the predictions weren't accurate. They were either way too high or too low. For now, we're turning it off and in the future we'll be adding spending limits and will revisit this then.
- Removed the usage code from the <Usage/> component
- Removed the usage components from the usage route
- Adjust the layout so the number

Removed the inaccurate usage prediction bar

---

apps/webapp/app/components/primitives/TreeView/TreeView.tsx
apps/webapp/app/v3/services/resumeTaskDependency.server.ts
references/hello-world/src/trigger/prioritize-continuing.ts

When we try and resume after `triggerAndWait` or `batchTriggerAndWait` the run is put back into the queue, if there's a checkpoint and the run is no longer in the cluster.
We were enqueue to the back of the queue, because we weren't setting a timestamp. This meant you ended up with a lot of frozen runs and we were prioritizing starting new runs vs finishing existing ones.
Now when we enqueue we add the parent run's createdAt as the timestamp which gives it the correct position in the queue.

Prioritize finishing waited runs

---

apps/coordinator/src/index.ts

In very rare cases sending socket messages with ACKs can throw. Specifically, when requests are mid-flight and the socket disconnects. This should catch all those errors.

Prevent uncaught socket ack exceptions

---

docs/context.mdx
docs/mint.json
packages/core/src/v3/schemas/common.ts

Added a new Context page for the docs

---

.changeset/giant-mugs-clean.md
apps/webapp/app/v3/marqs/sharedQueueConsumer.server.ts
packages/core/src/v3/errors.ts
packages/core/src/v3/links.ts
packages/core/src/v3/schemas/common.ts

Runs locked to very old SDK versions `< beta.25` would previously get stuck in a queued state. This will crash those runs instead and advise uprading to latest.

Add and use new internal error for very outdated SDK versions

---

.changeset/modern-nails-refuse.md
packages/core/src/v3/apiClient/runStream.ts
packages/core/test/runStream.test.ts
scripts/publish-prerelease.sh

Previously subscribing to a single realtime stream would block other run updates and streams from being consumed, this update fixes it so multiple streams can be consumed at once and they don't block the run updates from being consumed.

Multiple streams can now be consumed at the same time

---

.changeset/shaggy-donkeys-hammer.md
apps/webapp/app/v3/services/finalizeTaskRun.server.ts
packages/core/src/v3/apiClient/runStream.ts
packages/core/src/v3/schemas/api.ts
references/nextjs-realtime/src/trigger/example.ts

This fixes an issue with cancelled runs and other runs in an error state that would cause realtime to throw an error because we weren't using the correct schema for the `error` column. I've also made setting the final run status and error atomic to prevent realtime from closing the subscription too early.

Fix cancelled runs breaking realtime subscriptions

---

.changeset/sweet-suits-kick.md
apps/webapp/app/routes/api.v1.tasks.batch.ts
apps/webapp/app/routes/api.v3.runs.$runId.ts
apps/webapp/app/services/routeBuilders/apiBuilder.server.ts
apps/webapp/app/services/worker.server.ts
apps/webapp/app/v3/services/batchTriggerV2.server.ts
docker/docker-compose.yml
internal-packages/testcontainers/src/utils.ts
packages/core/src/v3/apiClient/index.ts
packages/core/src/v3/types/tasks.ts
packages/trigger-sdk/src/v3/shared.ts
references/v3-catalog/src/trigger/batch.ts

This PR adds an option to the batch trigger endpoints and SDK methods to make sure batched items are triggered sequentially, which is the way the deprecated batch trigger works:
```ts
await tasks.batchTrigger([], { triggerSequentially: true })
```
This option is available to all the batch trigger SDK methods.
This PR also fixes an issue that was causing 404s when calling `runs.retrieve` to not retry, which is an issue with the new batch endpoint that eventually creates runs, instead of transactionally.

Optionally trigger batched items sequentially to preserve order

---

apps/webapp/app/v3/handleSocketIo.server.ts

If lazy attempt creation and payload retrieval failed after the attempt status was already set to `EXECUTING`, the retry would previously fail due to status checks.

Fix: Prevent some attempt creation retries from causing system failures

---

.changeset/poor-shirts-move.md
.changeset/silent-trees-jump.md
packages/core/src/v3/apiClient/runStream.ts
packages/core/src/v3/schemas/api.ts

- Adds a polyfill for ReadableStream[@@asyncIterator], which for some reason Safari still does not support
- Adds missing TIMED_OUT TaskRunStatus case
- Fixes realtime date coercion by forcing UTC (which they will always be).

Realtime fixes: safari, timezones, and TIMED_OUT status

---

apps/webapp/app/v3/services/completeAttempt.server.ts

The deploy run controller is unaware of attempt submission outcomes, especially after OOM errors. The decision to retry on a larger machine is made by the webapp and there is no direct two-way communication.
To fix this, we'll send the same graceful exit request to the run that is also used in other places. Retry delay spans have also been improved with additional info.

Fix run container exits after OOM retries

---

apps/docker-provider/src/index.ts
apps/kubernetes-provider/src/index.ts

This will allow us to show more detailed metrics and debug cold starts better.

Add scheduled at timestamp to created run containers

---

apps/webapp/app/components/navigation/SideMenu.tsx
apps/webapp/app/components/primitives/Popover.tsx

Fixes the truncation when project names are too long.
Also prevents the dropdown chevron icon getting too small

Fixes missing truncation on the project name text

---

apps/webapp/app/presenters/v3/QueueListPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.queues/route.tsx

- Fix for the queues showing when they shouldn't have been (i.e. on v3)
- Fix for bad docs link to upgrade to v4 guide

Queues page: fix for upgrade state, and upgrade docs link

---

internal-packages/database/prisma/migrations/20250318163201_add_previous_snapshot_id_to_task_run_execution_snapshot/migration.sql

The new checksum of the migration is `578158878714a085ae9804646fa114be4bf0f873fd9677112246537c4e5e6831`

fix: update migration with the "Drop/Add" index of SecretStore key

---

packages/core/src/v3/apiClient/index.ts

This will allow migrating to the v4 SDK in your application backend before deploying v4 to trigger, and everything will just work

fix: only pass engine version header when inside a task

---

internal-packages/run-engine/src/engine/systems/checkpointSystem.ts

This should fix resuming runs after a batchTriggerAndWait where we've done a checkpoint

We weren’t copying the batch info when suspending a run

---

apps/webapp/app/v3/services/createBackgroundWorker.server.ts
packages/core/src/v3/resource-catalog/standardResourceCatalog.ts
packages/core/src/v3/types/tasks.ts
packages/trigger-sdk/src/v3/shared.ts
references/hello-world/src/trigger/release-concurrency.ts

There was an issue with `releaseConcurrencyOnWaitpoint` being set when indexing. It was registered twice, once for the custom queue and again where it was being used on any tasks. On the task registrations it didn't pass through `releaseConcurrencyOnWaitpoint` and this was "winning".
- Now we allow setting `releaseConcurrencyOnWaitpoint` directly on a task queue.
- Fixed custom queues not working with releaseConcurrencyOnWaitpoint
- We show an error if you register the same queue twice but with different settings (but continue).

Fix: custom queue releaseConcurrencyOnWaitpoint.

---

apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.waitpoints.tokens.$waitpointParam/route.tsx

Removes hard coded “5” from “5 related runs” in the waitpoint tokens page inspector

Removes hard coded “5” from “5 related runs” in the waitpoint tokens page inspector

---

apps/webapp/app/presenters/v3/RunPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.runs.$runParam/route.tsx
apps/webapp/app/v3/runEngineHandlers.server.ts

If you have concurrency limits set you can end up with queue times greater than a few seconds if you add many items to your queue.
This makes the run timeline really annoying because the queue time dominates the horizontal space, making it hard to tell what happened when your code started executing.
This PR makes it so this queue time is hidden by default, and can be turned back on using a toggle (or pressing "Q" on the keyboard).
Fixes
- The v4 retry attempt spans getting placed in the wrong order in the tree.
- The duration numbers expanded/squished while the timeline was animating, this is now fixed.

Don't show queue time in the run timeline by default

---

internal-packages/database/prisma/migrations/20250417135530_task_schedule_dashboard_indexes/migration.sql

They've already been applied and Prisma won't apply two in a single file…

Change schedule indexes to be created non-concurrently

---

packages/redis-worker/src/queue.test.ts
packages/redis-worker/src/queue.ts

Somehow there were orphaned items in the RedisWorker queue (had a queue entry but no item). These started filling up the queue which means real work wasn't being done.
Changes
1. Clean up orphaned queue entries if the item doesn't exist.
2. Removed duplicate setting of invisibility timeout (it was already set correctly in the dequeued script).
3. Added tests for orphan removal. 
4. Improved invisibility timeout test

RedisWorker clean up orphaned items when dequeuing

---

.changeset/wet-steaks-reflect.md
packages/cli-v3/src/commands/deploy.ts

Closes #1990 
If you pass in a directory that isn't found, we tell you it doesn't exist and where we looked.
If you pass in `prod` `staging` `stg` or `production` we tell you how you should be running the command: `--env prod` or `--env staging`. Please note you don't need to pass `prod` it's the default.

Give helpful hint if you pass a bad directory when deploying

---

apps/webapp/app/env.server.ts
apps/webapp/app/models/user.server.ts
apps/webapp/app/routes/login._index/route.tsx
apps/webapp/app/services/email.server.ts
apps/webapp/app/utils/boolEnv.ts
apps/webapp/app/utils/email.ts

No magic link emails will be sent out to non-whitelisted emails. GitHub auth is now also covered and errors will be displayed.
Also includes a fix for boolean env vars. The following env vars always evaluated to true if any value was set:
- MARQS_DISABLE_REBALANCING
- RUN_ENGINE_DEBUG_WORKER_NOTIFICATIONS
- SMTP_SECURE
- ALERT_SMTP_SECURE
Thanks @Kritik-J for the prior work on this! And sorry it took us so long to get this in :face_with_peeking_eye: 
Fixes #833

Improve email whitelisting and extend to GitHub auth

---

.changeset/gold-insects-invite.md
.changeset/wild-mirrors-return.md
packages/cli-v3/src/build/bundle.ts
packages/core/src/v3/config.ts
references/v3-catalog/src/trigger/binaries.ts
references/v3-catalog/trigger.config.ts

The `minify` option can decrease bundle sizes by up to half, if not more. It could also break a lot of stuff, hence experimental.
The `keepNames` option can fix issues in frameworks like MikroORM. Unsure about potential to break things, but best to be safe.
Both disabled by default.

Expose esbuild `keepNames` and `minify` options (experimental)

---

apps/webapp/app/presenters/v3/ScheduleListPresenter.server.ts
apps/webapp/app/v3/services/registerNextTaskScheduleInstance.server.ts
apps/webapp/app/v3/services/upsertTaskSchedule.server.ts
apps/webapp/app/v3/utils/calculateNextSchedule.server.ts
apps/webapp/test/calculateNextSchedule.test.ts

As they always follow a deterministic step (instead of an interval from an non-deterministic starting point) and previous timestamps don't matter

fix: calculating next schedule should always just be from now

---

.changeset/late-dancers-smile.md
.cursorignore
packages/cli-v3/src/cli/index.ts
packages/cli-v3/src/commands/analyze.ts
packages/cli-v3/src/commands/dev.ts
packages/cli-v3/src/dev/backgroundWorker.ts
packages/cli-v3/src/dev/devOutput.ts
packages/cli-v3/src/dev/devSession.ts
packages/cli-v3/src/dev/devSupervisor.ts
packages/cli-v3/src/dev/workerRuntime.ts
packages/cli-v3/src/entryPoints/dev-index-worker.ts
packages/cli-v3/src/entryPoints/managed-index-worker.ts
packages/cli-v3/src/indexing/registerResources.ts
packages/cli-v3/src/utilities/analyze.ts
packages/core/src/v3/schemas/build.ts

The dev command will now print warnings for slow imports with helpful tips to remedy this.
New flags:
- `--analyze` for detailed output
- `--disable-warnings` to stop printing warnings

Feat: import timings and bundle size analysis

---

.changeset/fuzzy-snakes-beg.md
apps/supervisor/src/env.ts
apps/supervisor/src/index.ts
apps/supervisor/src/workloadServer/index.ts
apps/webapp/app/routes/engine.v1.dev.runs.$runFriendlyId.logs.debug.ts
apps/webapp/app/routes/healthcheck.tsx
packages/core/src/v3/runEngineWorker/supervisor/http.ts
packages/core/src/v3/runEngineWorker/supervisor/session.ts
packages/core/src/v3/runEngineWorker/supervisor/types.ts

- Controlled via supervisor env var: `SEND_RUN_DEBUG_LOGS`
- Permanently disabled at the webapp route level for dev runs
- Also replaces webapp health check with a more lightweight sql query

Optionally disable run debug logs

---

apps/webapp/app/routes/metrics.ts

Grafana requires:
- `# EOF` marker at the end
- No empty lines

Fix metrics format

---

apps/webapp/app/presenters/v3/ScheduleListPresenter.server.ts
apps/webapp/app/routes/api.v1.projects.$projectRef.envvars.$slug.import.ts
apps/webapp/app/services/upsertBranch.server.ts
apps/webapp/app/v3/services/checkSchedule.server.ts
apps/webapp/app/v3/services/createBackgroundWorker.server.ts
apps/webapp/app/v3/services/createDeploymentBackgroundWorker.server.ts
packages/build/src/extensions/core/syncEnvVars.ts
packages/build/src/extensions/core/vercelSyncEnvVars.ts
packages/cli-v3/src/build/extensions.ts
packages/cli-v3/src/commands/deploy.ts
packages/cli-v3/src/commands/workers/build.ts
packages/core/src/v3/build/extensions.ts
packages/core/src/v3/schemas/api.ts
packages/core/src/v3/schemas/build.ts
references/hello-world/trigger.config.ts

syncEnvVars (and syncVercelEnvVars) would only sync the environment, not the parent environment's variables.
This is relevant for syncing preview env vars, where you want to set the "Preview" env vars AND the override for the specific environment (if there is an override).

Sync env vars (parent env vars)

---

packages/build/src/extensions/core/vercelSyncEnvVars.ts

Removed a log that always showed when using `syncVercelEnvVars()`

syncVercelEnvVars: remove visible log

---

apps/webapp/app/components/environments/EnvironmentLabel.tsx
apps/webapp/app/components/primitives/Tooltip.tsx

Here's a video of how we deal with long names
https://github.com/user-attachments/assets/f7efd5a0-30b9-4216-8204-46aa21b17e2e

Fix long preview branch names

---

packages/core/src/v3/apiClient/index.ts

Without the branch header it listens to the wrong environment

Preview branches fix: set the branch header for the SDK realtime functions

---

apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.alerts.new/route.tsx
apps/webapp/app/v3/services/alerts/deliverAlert.server.ts
apps/webapp/app/v3/services/alerts/performTaskRunAlerts.server.ts
internal-packages/emails/emails/alert-run-failure.tsx
packages/core/src/v3/schemas/webhooks.ts

Added support for preview branch alerts and format the messages

Preview branch alerts

---

.changeset/flat-pianos-live.md
packages/core/src/v3/utils/getEnv.ts

Less of this:
```ts
import { configure } from "@trigger.dev/sdk/v3";
configure({
secretKey: "tr_dev_…", // nasty, don't do this
});
```
More of that:
```
TRIGGER_SECRET_KEY="tr_dev_…"
```

Runtime agnostic SDK configuration via env vars

---

apps/webapp/app/database-types.ts
apps/webapp/app/services/platform.v3.server.ts
apps/webapp/app/services/telemetry.server.ts
internal-packages/database/prisma/migrations/20250526092407_remove_v2_tables_round_1/migration.sql
internal-packages/database/prisma/migrations/20250526093738_remove_v2_round_2/migration.sql
internal-packages/database/prisma/migrations/20250526094044_remove_v2_trigger_http_endpoint_environment/migration.sql
internal-packages/database/prisma/migrations/20250526094442_remove_v2_round_3/migration.sql
internal-packages/database/prisma/migrations/20250526094729_remove_v2_round_4/migration.sql
internal-packages/database/prisma/migrations/20250526095040_remove_v2_round_5/migration.sql
internal-packages/database/prisma/migrations/20250526095444_remove_v2_round_6/migration.sql
internal-packages/database/prisma/migrations/20250526095826_remove_v2_round_7/migration.sql
internal-packages/database/prisma/migrations/20250526100059_remove_v2_round_8/migration.sql
internal-packages/database/prisma/migrations/20250526100402_remove_v2_round_9/migration.sql
internal-packages/database/prisma/migrations/20250526100607_remove_v2_round_10/migration.sql
internal-packages/database/prisma/schema.prisma

Removed v2 models from the schema in a safe way (migrations can be run manually on the database before actually applying the migrations during deploy). Takes the schema down from 22,268 tokens (93378 characters) to 14,317 tokens (59810 characters), a savings of 35.7%

chore: remove v2 models from schema

---

.changeset/light-peas-melt.md
.env.example
apps/webapp/app/components/navigation/OrganizationSettingsSideMenu.tsx
apps/webapp/app/components/navigation/SideMenu.tsx
apps/webapp/app/env.server.ts
apps/webapp/app/services/email.server.ts
apps/webapp/app/services/upsertBranch.server.ts
docker/services-compose.yml
packages/cli-v3/src/commands/update.ts

- Remove unused env vars from webapp
- Increase branch limit fallback
- Do not display usage page when self-hosting
- Increase default org concurrency so the env default is correctly applied
- Fix CLI init flow so dev/deploy don't fail due to bad version string

A few small v4 fixes

---

docs/guides/example-projects/realtime-fal-ai.mdx

The video width was collapsing too 100 px because the unit was missing from the width value.

Docs: Fixes incorrect embeded video width size

---

.changeset/wicked-ads-walk.md
packages/core/src/v3/apiClient/stream.ts
references/hello-world/src/trigger/realtime.ts

Fixes an issue with realtime when re-subscribing to a run, that would temporarily display stale data and the changes. Now when re-subscribing to a run only the latest changes will be vended

Fix realtime re-subscribing stale data issue

---

docs/limits.mdx

Brought the limits.mdx up to date with the marketing site pricing page. 
I decided to keep the information in the docs rather than linking out to the pricing page because Kapa is indexed on the docs site and it would be good to make sure it can easily get the correct information from the MDX.

Docs: Added more limits and information to the limits page

---

docs/troubleshooting.mdx

Adds a docker error entry to common problems docs page

Docs: adds a docker error entry to common problems docs page

---

apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam._index/route.tsx
internal-packages/clickhouse/src/taskRuns.ts

- Since we switched to using ClickHouse to show the Tasks page statistics, the Queued count didn't include Delayed runs anymore. It used to.
- The mini-graph never included Delayed runs.

Tasks page didn't include Delayed runs

---

apps/webapp/app/components/ImpersonationBanner.tsx
apps/webapp/app/components/navigation/SideMenu.tsx

The impersonation button was causing a hydration error, which broke deferred requests. This was only an issue when impersonating.

Fix hydration error

---

apps/webapp/app/v3/services/rescheduleTaskRun.server.ts

Using `runs.reschedule()` wasn't working correctly. 
- In v3 a bug was introduced when we added the TaskRun `queueTimestamp` column.
- In v4 it wasn't implemented yet
This PR makes rescheduling work properly for both versions.

Delay reschedule fix (v3 & v4)

---

docker/Dockerfile

This fixes an issue where only the corepack shims were present in the final stage. We now include pnpm for both node and root users by default. The correct version specified in the package.json will be used.
Fixes #2178

Ensure webapp container does not fetch pnpm at runtime

---

apps/webapp/app/env.server.ts
apps/webapp/app/v3/alertsWorker.server.ts
apps/webapp/app/v3/commonWorker.server.ts
apps/webapp/app/v3/legacyRunEngineWorker.server.ts
apps/webapp/app/v3/scheduleEngine.server.ts
internal-packages/run-engine/src/engine/index.ts
internal-packages/schedule-engine/src/engine/distributedScheduling.ts
internal-packages/schedule-engine/src/engine/index.ts
internal-packages/schedule-engine/src/engine/types.ts
packages/redis-worker/src/worker.ts

Fixed the calculation for distributing schedules across the "calculation window" timeframe to include the schedule instanceId in the random seed and not just the schedule time, which was causing all schedules to be "distributed" into the exact same timestamp (not good).
Also fixed an issue where the schedule engine `workers` and `tasksPerWorker` options were not being passed down to the internal RedisWorker, causing the defaults of `1` and `10` to be used. 
I also added some additional logging into RedisWorker and also spaced-out the starting times of each run worker loop.

Improve schedule engine performance

---

.changeset/chilled-weeks-switch.md
packages/cli-v3/src/commands/update.ts

When a non-exact package version is installed we rely on the resolved `package.json` file of the respective package. We were incorrectly trying to extract this version from type markers instead of the root `package.json` which has the version info.
(this likely broke in v4 when we switched the main export to the v3 dir)

Fix update command version detection

---

docs/self-hosting/docker.mdx
docs/upgrade-to-v4.mdx
hosting/docker/webapp/docker-compose.yml
hosting/k8s/helm/Chart.yaml
hosting/k8s/helm/templates/supervisor.yaml
hosting/k8s/helm/templates/webapp.yaml
hosting/k8s/helm/values.yaml

- k8s-native worker token bootstrap
- auto s3 bucket creation for docker and k8s
- small docs fixes

Self-hosting: improved worker and bucket bootstrap

---

docs/triggering.mdx

Update example code in `docs/triggering.mdx` for `triggering from inside another task`.
When triggering from inside another task, `runs` and `batch` should be imported from `@trigger.dev/sdk/v3`.
If my understanding is incorrect and the best practice is to export `runs` and `batch` from `~/trigger/my-other-task` so it can be imported, please close this PR and clarify on the docs.

docs (triggering.mdx): triggering from inside another task

---

hosting/k8s/helm/Chart.yaml
hosting/k8s/helm/values.yaml

The prior `nano` preset sets a very low memory limit causing OOM errors even while testing.

helm: increase default postgres resource preset

---

docs/config/config-file.mdx
docs/snippets/node-versions.mdx
docs/upgrade-to-v4.mdx

Adds a snippet to show which node.js versions we use in v3 and v4. Snippet has been added to: 
- config-file.mdx
- upgrade-to-v4.mdx

Docs: Adds 2 references to the node.js versions we use for v3 and v4

---

docs/limits.mdx
docs/self-hosting/env/webapp.mdx
docs/self-hosting/overview.mdx

Document new otel limits

---

packages/core/src/v3/utils/ioSerialization.ts
references/hello-world/src/trigger/example.ts

Because superjson supports circular references (as in it will deserialize back into a circular reference) it isn't safe to `JSON.stringify` the result of `superjson.deserialize` without handling circular references. This PR makes use of a WeakSet to keep track of references and will output a `[Circular]` string whenever one is encountered:

Prevent circular references from breaking run logs in task outputs

---

apps/webapp/app/components/primitives/Select.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.test.tasks.$taskParam/route.tsx

This PR contains a few small changes for the test page:
- fixed scrollbars style in the options pane
- added missing field descriptions
- added a link to the docs section about run options
- updated the copy for the field descriptions in favor of brevity

fix: add missing field descriptions in the test page

---

docs/github-actions.mdx

It defaults to the latest buildx version _available in the runner_ which may not be the latest _published_ version. This would then break certain flags we use for local deploys that are unavailable in older versions.

fix(docs): force latest buildx version in sample gh action

---

.changeset/strong-pianos-provide.md
docs/github-actions.mdx
docs/snippets/cli-commands-deploy.mdx
packages/cli-v3/src/commands/login.ts
packages/core/src/v3/links.ts
packages/redis-worker/src/cron.test.ts

When you run deploy in CI, aren't logged in, and `TRIGGER_ACCESS_TOKEN` is _not_ set, there is now a very descriptive error message. You will not anymore be prompted to log in interactively. There's a link to the docs and the token page.
Also renamed the GitHub Actions page to CI / GitHub Actions to point users of other CI systems in the right directions. There's a new `Deploying from CI` section in the CLI deploy commands docs.
Fixes #2255

fix(deploy): fail in CI with descriptive message and instructions if no access token set

---

apps/webapp/app/components/code/JSONEditor.tsx
apps/webapp/app/components/runs/v3/ReplayRunDialog.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.test.tasks.$taskParam/route.tsx
apps/webapp/app/routes/resources.taskruns.$runParam.replay.ts
apps/webapp/app/v3/replayTask.ts
apps/webapp/app/v3/services/replayTaskRun.server.ts
apps/webapp/app/v3/testTask.ts

Changes in this PR:
- Added run options and metadata to the replay run modal.
- Rearranged the layout a bit.
- Fixed an issue with the clear button in the json editor component.

feat: enable overriding run options when replaying

---

docs/guides/ai-agents/generate-translate-copy.mdx

Ran into a small issue when following the example at https://trigger.dev/docs/guides/ai-agents/generate-translate-copy.  
This PR includes a minor fix to address it.
- Just made a small fix based on usage context; not a full local install.
- Didn't run the full project, but the change looks small and safe.
Manually verified that `generatedCopy.text` is rendered correctly in the template literal.
Fixed a bug where the AI-generated object was being passed instead of its `.text` value.
N/A

fix: use generatedCopy.text instead of full object

---

hosting/docker/webapp/docker-compose.yml

Previously, setting `NODE_MAX_OLD_SPACE_SIZE` in you `.env` would have no effect

fix(docker): apply max old space size env var to webapp

---

apps/webapp/app/routes/admin._index.tsx
apps/webapp/app/routes/admin.orgs.tsx

- Adds a Copyable text option on hover to all text entries in the Users and Orgs tables
- Autofocuses the search fields
- The search fields are medium size, not small

Copyable admin area table fields and autofocus search

---

hosting/docker/webapp/docker-compose.yml
hosting/k8s/helm/Chart.yaml
hosting/k8s/helm/templates/electric.yaml
hosting/k8s/helm/values.yaml

Previously, the postgres `DATABASE_URL` on the electric service could not be set from a secret. This also updates electric to the latest patch release.
Fixes #2281

fix(helm): allow electric db url var to be set from secret

---

apps/webapp/test/runsRepository.test.ts

The normal database needs to be mocked because an import somewhere is 
using it which causes issues with the test container dbs and hanging at 
the end. 
Strategy copied from the trigger test file.

Run repository test fix

---

package.json
pnpm-lock.yaml

security: bump form-data to latest patch versions (CVE-2025-7783)

---

apps/webapp/app/presenters/v3/ApiRetrieveRunPresenter.server.ts
references/hello-world/src/trigger/example.ts

fix runs.retrieve when the payload or output has unstringifiable JSON

---

docs/limits.mdx

Updates the concurrency pricing to the correct $50 for bundles of 50.

Docs: Fixes incorrect concurrency pricing on the limits page

---

apps/webapp/app/components/BlankStatePanels.tsx
apps/webapp/app/components/SetupCommands.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam._index/route.tsx

The Task page's blank state now shows: 
- The deploy CLI commands for Prod, Staging, Preview
- Links to the docs, troubleshooting and Ask AI (with tooltips explaining where they go)
- Links to GitHub actions docs page
- Page refreshes when tasks deployed

New Task page deploy blank state

---

.changeset/silent-lobsters-march.md
packages/build/src/extensions/playwright.ts
packages/cli-v3/src/utilities/windows.ts

Fixes #2226 
- **Improved Playwright chrome installation**: Enhanced non-headless chrome installation to ensure both chrome binaries are installed even when `headless: false` is specified
- **Fixed spinner duplication**: Resolved issue where spinner messages would duplicate on narrow terminals

fix(playwright): improve chrome installation and fix spinner duplication on narrow terminals

---

internal-packages/run-engine/src/engine/systems/dequeueSystem.ts
internal-packages/run-engine/src/engine/systems/runAttemptSystem.ts
internal-packages/run-engine/src/engine/tests/attemptFailures.test.ts
internal-packages/run-engine/src/engine/tests/waitpoints.test.ts

fix(engine): set correct run status after requeue and snapshot status after dequeue

---

apps/webapp/app/runEngine/concerns/idempotencyKeys.server.ts
apps/webapp/app/v3/eventRepository.server.ts
apps/webapp/app/v3/taskStatus.ts

If you trigger a run with an idempotency key but that run fails it won’t be returned as a cached run in v4. 
It’s hard to come up with a situation where you would want the old behaviour. If you did want to cache a failure, you should return a `Result` type instead of throwing an error. Failures should only be used when something has gone wrong, not to indicate a known false case.

Idempotency ignores failed runs in v4

---

internal-packages/run-engine/src/engine/errors.ts
internal-packages/run-engine/src/engine/index.ts
internal-packages/run-engine/src/engine/systems/checkpointSystem.ts
internal-packages/run-engine/src/engine/systems/executionSnapshotSystem.ts
internal-packages/run-engine/src/engine/systems/runAttemptSystem.ts
packages/core/src/logger.ts

We were acking the heartbeat in a couple of places which could cause problems if the run had transitioned execution status between the stall being dequeued and the code running.
We don’t need to ack it because the Redis worker deals with this exact situation if you just return – it acks ONLY if the deduplication key matches, otherwise it leaves the item there.
Also added some metadata logging to some of the ServiceValidationErrors because there are a few of these and I want to confirm they’re not real issues.

Fix for heartbeat race condition (acking)

---

apps/webapp/app/presenters/v3/BranchesPresenter.server.ts
apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.deployments/route.tsx

Small change that shows the github user in the deployments page in cases
where it was triggered by the github app integration.
These deployments are not triggered using a PAT, so we cannot associate
them with a Trigger user ID.

feat: show gh username and avatar for deployments triggered by the github app integration

---

.changeset/proud-nails-grin.md
apps/supervisor/src/env.ts
apps/supervisor/src/envUtil.ts
apps/supervisor/src/index.ts
apps/supervisor/src/workloadManager/kubernetes.ts
apps/supervisor/src/workloadManager/types.ts
apps/webapp/app/env.server.ts
apps/webapp/app/routes/resources.orgs.$organizationSlug.select-plan.tsx
apps/webapp/app/runEngine/concerns/queues.server.ts
apps/webapp/app/runEngine/services/batchTrigger.server.ts
apps/webapp/app/runEngine/services/triggerTask.server.ts
apps/webapp/app/runEngine/types.ts
apps/webapp/app/runEngine/validators/triggerTaskValidator.ts
apps/webapp/app/services/platform.v3.server.ts
apps/webapp/app/utils/boolEnv.ts
apps/webapp/app/v3/runEngine.server.ts
apps/webapp/app/v3/services/triggerTask.server.ts
apps/webapp/package.json
internal-packages/cache/src/index.ts
internal-packages/database/prisma/migrations/20250814092224_add_task_run_plan_type/migration.sql
internal-packages/database/prisma/schema.prisma
internal-packages/run-engine/src/engine/billingCache.ts
internal-packages/run-engine/src/engine/index.ts
internal-packages/run-engine/src/engine/systems/dequeueSystem.ts
internal-packages/run-engine/src/engine/types.ts
packages/core/src/v3/schemas/runEngine.ts
pnpm-lock.yaml

Enables runs to be scheduled on specific nodes based on configurable placement tags. The system uses k/v pairs, with billing information automatically converted to placement tags during dequeue.
- `PLACEMENT_TAGS_ENABLED=false` - Enable placement tags scheduling (default: false)
- `PLACEMENT_TAGS_PREFIX=node.cluster.x-k8s.io` - Kubernetes label prefix for placement tags (default shown)
- `BATCH_TRIGGER_CACHED_RUNS_CHECK_ENABLED` - Whether to perform potentially expensive checks (default: `false`)
All placement tag scheduling is disabled by default and schema changes are optional.

feat(k8s): add placement tags for flexible node selection

---

apps/webapp/app/components/Shortcuts.tsx
apps/webapp/app/routes/resources.orgs.$organizationSlug.projects.$projectParam.env.$envParam.runs.$runParam.spans.$spanParam/route.tsx

We accidentally shipped the shortcut for "Cancel run" button as "C" which conflicts with toggling to the "Context" tab on the run page.
- The Context tab shortcut is now "X"
- The shortcut help panel is also update to match

Fixes conflicting shortcut keys

---

docs/config/extensions/lightpanda.mdx
docs/guides/examples/lightpanda.mdx
docs/guides/frameworks/bun.mdx
docs/guides/frameworks/nextjs.mdx
docs/guides/frameworks/supabase-edge-functions-basic.mdx
docs/guides/frameworks/supabase-edge-functions-database-webhooks.mdx

- removed incorrect version info
- fixed node cli warning that wasn't displaying before
- moved known issues to the top
- also removed references to snippets that don't exist anymore across the docs

chore(docs): update bun guide

---

apps/webapp/app/env.server.ts
apps/webapp/app/v3/marqs/index.server.ts
apps/webapp/app/v3/marqs/marqsKeyProducer.ts
apps/webapp/app/v3/marqs/sharedQueueConsumer.server.ts
apps/webapp/app/v3/marqs/types.ts

We will now dequeue into a redis list as many messages as we possibly 
can from actual queues, trying to dequeue up to 10 runs at a time for 
each queue in an env, in separate queue consumers. Then the 
SharedQueueConsumer can simply `lpop` off that list and process a run to
be dequeued very quickly. This should get runs through the platform side
dequeue system very quickly.

fix(v3): adopt v4 dequeue strategy to increase perf

---

docs/triggering.mdx

Update the docs triggering.mdx - text indicating options argument position:
- Options object is a third argument instead of stated second argument (`trigger` function)
- Options object is a third argument instead of stated second argument (`batchTrigger` function)

docs: update triggering.mdx fixing wrongly stated argument position for options

---

apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.regions/route.tsx

Adds a little message to explain the difference between run execution locations vs data residency

Regions page: show a message to explain about data residency

---

apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.regions/route.tsx

Updates the Regions page message with more accurate text about GDPR
- Security portal link goes to our security page: https://security.trigger.dev
- Get in touch brings up the Feedback modal for a general enquiry

chore(webapp): update region message to say we are GDPR compliant

---

hosting/docker/webapp/docker-compose.yml

The healthcheck for clickhouse used the default username/password and would cause an error if you changed it

fix(docker): clickhouse healthcheck

---

apps/webapp/app/v3/getDeploymentImageRef.server.ts
apps/webapp/app/v3/services/initializeDeployment.server.ts
apps/webapp/test/getDeploymentImageRef.test.ts

```
Old tags: 20250903.1.preview-some-branch
New tags: 20250903.1.preview-some-branch.1234abcd
```
fixes #2473

fix(webapp): prevent duplicate preview env image tags

---

apps/supervisor/src/env.ts
apps/supervisor/src/workloadManager/kubernetes.ts

Adds environment variables to configure Kubernetes resource requests with customizable CPU/memory ratios and minimum values. Defaults preserve existing behavior when not configured.
- `KUBERNETES_CPU_REQUEST_MIN_CORES` - Minimum CPU cores to request (e.g. `0.5`), defaults to `0`
- `KUBERNETES_MEMORY_REQUEST_MIN_GB` - Minimum memory GB to request (e.g. `2`), defaults to `0`
- `KUBERNETES_CPU_REQUEST_RATIO` - Ratio of CPU limit to request (e.g. `0.75` for 75%), defaults to `0.75`
- `KUBERNETES_MEMORY_REQUEST_RATIO` - Ratio of memory limit to request (e.g. `1` for 100%), defaults to `1`

feat(supervisor): make resource request ratios configurable

---

.changeset/serious-doors-call.md
packages/cli-v3/src/cli/index.ts
packages/cli-v3/src/commands/env.ts

This PR adds a couple of env commands to list and view environment variables
of a project. The `env pull` command also enables exporting the env vars into a file.
We might extend this to also support creating and deleting env vars in the future.

feat: env command in the cli 

---

apps/webapp/app/routes/resources.taskruns.$runParam.replay.ts
apps/webapp/test/fairDequeuingStrategy.test.ts
packages/core/src/v3/utils/ioSerialization.ts
packages/core/test/ioSerialization.test.ts
references/hello-world/src/trigger/circularPayload.ts

This also fixes an issue with replaying of runs that include 
non-circular references

fix(core): prettyPrintingPacket will now do a structuredClone on non-circular references instead of outputting [Circular]

---

.changeset/beige-flies-fail.md
packages/cli-v3/package.json
server.json

See: 
https://blog.modelcontextprotocol.io/posts/2025-09-08-mcp-registry-preview/

chore(mcp): Add our MCP server to the official MCP registry

---

apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.branches/route.tsx
apps/webapp/app/routes/api.v1.projects.$projectRef.branches.archive.ts
apps/webapp/app/routes/api.v1.projects.$projectRef.branches.ts
apps/webapp/app/routes/resources.branches.archive.tsx
apps/webapp/app/services/archiveBranch.server.ts
apps/webapp/app/services/upsertBranch.server.ts

Adjusts the authentication in a couple of endpoints to accept OATs too.

feat(api): accept OATs in preview branch related endpoints

---

apps/webapp/app/runEngine/services/triggerTask.server.ts
apps/webapp/app/runEngine/types.ts
apps/webapp/test/engine/triggerTask.test.ts
internal-packages/run-engine/src/engine/index.ts
internal-packages/run-engine/src/engine/systems/waitpointSystem.ts
internal-packages/run-engine/src/engine/tests/triggerAndWait.test.ts

The tests in this PR don't actually test and verify the race condition, but they do test and verify that trying to create two runs with the same idempotency key, with one winning and one throwing a prisma p2002 error, results in the correct behavior. I originally thought this was what was causing the issue, and we didn't have tests for that behavior, so I added them. But the tests passed, leading me to find what the real cause of the issue was: a race between finding the task run with an idempotency key, and the associated waitpoint of that run being created. The fix was the create the associated waitpoint in a prisma [nested write](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#nested-writes), which is in a transaction.

fix(engine): prevent race condition that prevents triggerAndWait runs from resuming by atomically creating associated waitpoint records

---

.changeset/six-cougars-play.md
apps/supervisor/src/workloadServer/index.ts
packages/cli-v3/src/entryPoints/managed/controller.ts
packages/cli-v3/src/entryPoints/managed/execution.ts
packages/cli-v3/src/entryPoints/managed/snapshot.test.ts
packages/cli-v3/src/entryPoints/managed/snapshot.ts
packages/core/src/v3/runEngineWorker/workload/http.ts

Other changes:
- supervisor: use lightweight mock route when debug logs are disabled

fix(runner): reduce restore recovery time and deprecated runner false positives

---

apps/webapp/app/components/primitives/CopyableText.tsx
apps/webapp/app/routes/resources.orgs.$organizationSlug.projects.$projectParam.env.$envParam.runs.$runParam.spans.$spanParam/route.tsx

You can now more easily copy data from the Details tab on the run page:
- Copy buttons on hover for task name, root/parent, version, batch, run id, internal id
- Adds `asChild` to the CopyableText component to prevent illegal button in button markup
- Improves the copy for consistency in some of the tooltips
https://github.com/user-attachments/assets/a428e87b-67c9-48cf-bfde-c1cfe58c266d

Chore(webapp): adds more copy buttons

---

.changeset/kind-kids-teach.md
apps/webapp/app/components/runs/v3/DeploymentStatus.tsx
apps/webapp/app/routes/api.v1.deployments.$deploymentId.progress.ts
apps/webapp/app/v3/services/deployment.server.ts
internal-packages/database/prisma/migrations/20250923182708_add_installing_status_to_deployments/migration.sql
internal-packages/database/prisma/schema.prisma
packages/cli-v3/src/commands/deploy.ts
packages/core/src/v3/schemas/api.ts

This PR adds a new status if the deployment lifecycle: `INSTALLING`. This is
relevant only for deployments triggered by the build server, with locally
triggered deployments the install stage is done on the client side.
Now we have a `/progress` endpoint which allows progressing from `PENDING` to
`INSTALLING` and then to `BUILDING`, which can be further extended in the future
if we have new statuses. The short-lived Depot build token is only created before
moving to the `BUILDING` status to avoid expiration issues.
The `/start` endpoint is superseded by the newer `/progress` endpoint. Removing
it won't cause trouble as it is not yet used in the SDK or documented in the
API docs.

feat: installing status for deployments

---

apps/webapp/app/models/member.server.ts
apps/webapp/app/routes/invite-accept.tsx
apps/webapp/app/routes/invite-resend.tsx
apps/webapp/app/routes/invite-revoke.tsx
apps/webapp/app/routes/invites.tsx

Fixes some scoping issues with team invites.

fix(webapp): org invite scoping

---

apps/webapp/app/routes/_app.orgs.$organizationSlug.settings.billing-alerts/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.settings.billing/route.tsx
apps/webapp/app/routes/_app.orgs.$organizationSlug.settings.usage/route.tsx
apps/webapp/app/routes/account.tokens/route.tsx
apps/webapp/app/routes/resources.orgs.$organizationSlug.select-plan.tsx
apps/webapp/app/services/personalAccessToken.server.ts

Adds proper org scoping in a few places in the app.

fix(webapp): org scoping issues in plan selection, alerts, pats and usage

---

apps/webapp/app/models/member.server.ts

We currently use CUIDs for invite tokens, which are generated using
a pattern and are not cryptographically secure. This PR switches to
a higher entropy string generated with `nanoid`.
Will remove the default value in the prisma schema in a separate PR.

fix: use higher entropy invite tokens

---

internal-packages/run-engine/src/engine/systems/waitpointSystem.ts

The `completeWaitpoint` method ignores Prisma update errors of type `P2025` to
handle concurrent attempts to complete a waitpoint token. We have an
error hook on the Prisma client which logs these errors though.
This PR switches to `updateMany` which doesn't throw an error if the
waitpoint is in an unexpected state. The behavior remains otherwise
unchanged. We currently continue even if the waitpoint is not in `PENDING`,
which could lead to race conditions in certain corner cases, though very
unlikely. We added a log line to see how often concurrent completion
attempts happen.

fix(run-engine): waitpoint update misleading error logs

---

README.md

This means DeepWiki will automatically re-index our repo and keep our page fresh

chore: add deepwiki badge to main readme

---

apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.settings/route.tsx
apps/webapp/app/services/projectSettings.server.ts
apps/webapp/app/services/projectSettingsPresenter.server.ts

The build server already handles this case gracefully, but doesn't hurt showing an early hint when preview deployments are disabled.

fix(webapp): disable gh-triggered preview deployments if the preview env is disabled
