- apps/webapp/app/entry.client.tsx
- apps/webapp/app/entry.server.tsx
- apps/webapp/package.json
- pnpm-lock.yaml
References this issue https://github.com/remix-run/remix/issues/2947
> Fix for refresh causing server/client mismatch. Using Remix's latest entry.*.ts files

- .dockerignore
- apps/webapp/package.json
- apps/webapp/server.ts
- docker/Dockerfile
- docker/scripts/entrypoint.sh
- pnpm-lock.yaml
PR to update the docker image with [best practices](https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/).
1. Switched to explicit image tags
2. Stopped copying files and running the container as root
3. Safely terminate the node process by installing/starting the app with `dumb-init` (tested by using the example from the best practices guide)
4. Handle shutdowns gracefully by installing/using [Terminus](https://github.com/godaddy/terminus). I went through the [graceful shutdown express documentation](https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html) for recommendations.
This was tested by adding a dummy `/test` endpoint with a delay. I made a request to this endpoint and then I made a request to kill the docker container before a …
> feat: 🎸 update Docker image to use best practices

- CONTRIBUTING.md
**Updated contributing README by adding the following:**
- Added missing `build` step before seeding
- Added troubleshooting for `PORT already in use` issue
> Fix: Updated contributing README for running in development

- docs/documentation/concepts/runs.mdx
From what I can tell, it is expected for run functions to return with some sort of payload. Providing an example here as a reference and guideline.
> docs: Update runs.mdx

- packages/express/src/index.ts
Small fix that jumped out while reading the Express server code
> fix: small typo in function docblocks

- packages/trigger-sdk/src/io.ts
> feat: parse callback result with zod before return

- .changeset/ten-oranges-pretend.md
- packages/cli/src/commands/init.ts
> fix: CLI init now logs the correct app route path.

- .changeset/neat-roses-wait.md
- examples/job-catalog/src/openai.ts
- integrations/openai/package.json
- integrations/openai/src/index.ts
- integrations/openai/src/taskUtils.ts
- integrations/openai/src/tasks.ts
- pnpm-lock.yaml
This upgrades the `@trigger.dev/openai` integration to use the new v4 version of the openai sdk:
https://github.com/openai/openai-node/discussions/217
Still TODO:
> #344 Upgrading the openai package to v4

- docs/documentation/guides/self-hosting/flyio.mdx
Fixes #339 
https://github.com/triggerdotdev/fly.io/pull/3 will also have to be merged
> docs: fix fly.io direct connection url

- .changeset/mighty-melons-vanish.md
- packages/cli/src/commands/init.ts
> fix: CLI init doesn't work outside of a GIT repo

- .changeset/lovely-teachers-taste.md
- packages/eslint-plugin/lib/rules/no-duplicated-task-keys.js
- packages/eslint-plugin/tests/lib/rules/no-duplicated-task-keys.js
- feat: select node by property key name
- feat: get `IfStatement`s recursively
- refactor: make `getNodeBody` more readable
- refactor: enshorter rule code
> fix/TRI 1149/cover all duplicated cases

- apps/webapp/app/models/jobRunExecution.server.ts
- apps/webapp/app/routes/api.v1.endpoints.$environmentId.$endpointSlug.index.$indexHookIdentifier.ts
- apps/webapp/app/services/endpointApi.server.ts
- apps/webapp/app/services/endpoints/createEndpoint.server.ts
- apps/webapp/app/services/endpoints/recurringEndpointIndex.server.ts
- apps/webapp/app/services/endpoints/validateCreateEndpoint.server.ts
- apps/webapp/app/services/events/ingestSendEvent.server.ts
- apps/webapp/app/services/runs/continueRun.server.ts
- apps/webapp/app/services/runs/performRunExecutionV2.server.ts
- apps/webapp/app/services/runs/startRun.server.ts
- apps/webapp/app/services/sources/handleHttpSource.server.ts
- apps/webapp/app/services/tasks/performTaskOperation.server.ts
> refactor: reduced max retries on some specific tasks on development endpoints

- docker/Dockerfile
- packages/database/package.json
Closes #566 
---
- Ran the code locally and update prsima to 5.4.1
- Created Nextjs project and make sure Jobs are run successfully
---
- Upgraded prisma from 4.16.0 to 5.4.1
---
💯
> update prisma to 5.4.1

- apps/webapp/app/routes/api.v1.sources.http.$id.ts
Relates to #585. 
This adds a catch and some logging. This won't solve the issue but should give us some more information on what's happening so it can be fixed. I've been unable to reproduce this issue locally.
> Try and determine an error some HTTP requests are causing

- .github/workflows/pr_checks.yml
This is to test the new pr_checks.yml workflow
> Pushing a commit to the branch so I can open a PR

- README.md
Fixed #593 Added Contributors Section to readme.md
- [✅] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [✅] The PR title follows the convention.
- [✅] I ran and tested the code works.
---
💯
> Fixed #593 Added Contributors Section to readme.md

- apps/webapp/app/utils/sse.ts
> Fix typo in sse.ts

- apps/webapp/app/components/primitives/Switch.tsx
- apps/webapp/app/hooks/useFilterJobs.ts
- apps/webapp/app/hooks/useToggleFilter.ts
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam._index/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.integrations/route.tsx
---
- Verified that the toggle filters the active jobs.
- Verified that all jobs are listed when the toggle is inactive 
---
- Add `useToggleFilter` which filters items based on `toggle` status.
- Use `useToggleFilter` in the `useFilterJobs` hook.
---
https://github.com/triggerdotdev/trigger.dev/assets/132386067/e73df1e5-b2da-43cb-8cd6-1063bc305283
💯
> feat: add filter for active jobs in the dashboard

- docs/documentation/quickstarts/astro.mdx
- docs/documentation/quickstarts/express.mdx
- docs/documentation/quickstarts/fastify.mdx
- docs/documentation/quickstarts/nestjs.mdx
- docs/documentation/quickstarts/nextjs.mdx
- docs/documentation/quickstarts/nuxt.mdx
- docs/documentation/quickstarts/redwood.mdx
- docs/documentation/quickstarts/remix.mdx
- docs/documentation/quickstarts/sveltekit.mdx
Closes #631 
---
ran it locally using mintlify dev 
works as it should be working
---
Added icons of the frameworks in side bar which were closest to their actual logo
---
💯
> framework icons added

- docs/integrations/apis/plain-tasks.mdx
- docs/integrations/apis/plain.mdx
- docs/mint.json
Closes #657 
---
I locally deployed the Docs Website using Netlify and verified all the changes.
https://github.com/triggerdotdev/trigger.dev/assets/47860497/55b18d2e-38ac-4c2a-b4c7-19e52b9acd76
---
The Plain Documentation has been updated such that it follows the same format as the GitHub Integration.
Plain Documentation is now divided into two sections.
- Plain Overview and Authentication
- Plain tasks
---
> [TRI-1425] : Improve the Plain integration documentation.

- README.md
---
I have changed the title and viewed it through live server
---
I have changed the title for the contributors since before one was not understandable
---
💯
> changed the title for contributors

- apps/webapp/app/presenters/RunListPresenter.server.ts
Closes #641 
---
- Tested page navigation for job runs with multiple pages.
- Ensure page navigation is not displayed for job runs with a single page.
---
Fix previous and next cursor calculation in `RunListPresenter`.
---
https://github.com/triggerdotdev/trigger.dev/assets/132386067/264ba088-e57a-44da-96d6-e7dfcff47904
💯
> fix: set correct next/prev cursors in run-list-presenter

- packages/cli/src/commands/init.ts
Closes #655 
---
---
Added warning -> ⚠️ Warning: We don't currently support long-running servers! For more details, check out [issue #244](https://github.com/triggerdotdev/trigger.dev/issues/244).
---
💯
> Added warning ⚠️ - No support for long-running servers

- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.triggers._index/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.triggers.scheduled/route.tsx
Changed TableBlankRow colSpan in scheduled/ external Triggers to 100%
Wasnt uniform looking.
See here:
---
💯
> BlankRow centered  in /Triggers

- .changeset/afraid-lies-listen.md
- packages/nextjs/package.json
- pnpm-lock.yaml
---
Created a fresh new Next.js 14 app and tested it locally and on production
---
Updates the `@trigger.dev/nextjs` package to work with Next.js 14
> Update `@trigger.dev/nextjs` to support Next.js 14

- .changeset/strange-schools-boil.md
- apps/webapp/app/routes/api.v2.$endpointSlug.triggers.$id.registrations.$key.ts
- packages/trigger-sdk/src/apiClient.ts
- packages/trigger-sdk/src/triggerClient.ts
- packages/trigger-sdk/src/triggers/dynamic.ts
---
Verified Dynamic Trigger registration & re-registration, ensured that a single event dispatcher is created for both cases.
---
Append a `nanoid` to uniquely identify the dynamic trigger source registration event.
---
💯
> fix: append nanoid for dynamic trigger reg event

- apps/webapp/.storybook/preview.tsx
---
Viewed the stories to verify they worked as expected.
---
This is a regression of the Remix upgrade.
💯
> fix: remove unstable createRemixStub in storybook

- apps/webapp/app/platform/zodWorker.server.ts
- apps/webapp/app/services/db/pgListen.server.ts
- apps/webapp/app/services/db/pgNotify.server.ts
- apps/webapp/app/services/db/types.ts
- apps/webapp/app/services/worker.server.ts
- apps/webapp/package.json
- pnpm-lock.yaml
Prep work for #524 
---
To simulate the intended behaviour, uncomment these lines:
https://github.com/triggerdotdev/trigger.dev/blob/71d16d81b30d8e3cf77b57765b8b5f0bef43fd00/apps/webapp/app/services/worker.server.ts#L125-L127
Multiple instances launched simultaneously - no workers should be forced to shut down.
Two instances launched >10s apart to simulate an upgrade - graceful shutdown shut be initiated on the first instance. This should also work for multiple instances launched at those time points.
---
- Add cross-instance notifications powered by Postgres NOTIFY
- Graceful worker shutdown on migration notification
- Add notification catalog
💯
> Feature: Cross-instance notification system

- .changeset/purple-bulldogs-sit.md
- apps/webapp/app/routes/api.v1.events.bulk.ts
- docs/_snippets/send-events-params.mdx
- docs/_snippets/send-events-return.mdx
- docs/mint.json
- docs/sdk/io/overview.mdx
- docs/sdk/io/sendevent.mdx
- docs/sdk/io/sendevents.mdx
- docs/sdk/triggerclient/instancemethods/sendevent.mdx
- docs/sdk/triggerclient/instancemethods/sendevents.mdx
- docs/sdk/triggerclient/overview.mdx
- packages/core/src/schemas/api.ts
- packages/trigger-sdk/src/apiClient.ts
- packages/trigger-sdk/src/io.ts
- packages/trigger-sdk/src/triggerClient.ts
- references/job-catalog/src/built-ins.ts
---
https://github.com/triggerdotdev/trigger.dev/blob/785ac2940f1178582df5da50d5cfdb0ea2df358d/references/job-catalog/src/built-ins.ts#L117-L146
> Feature: `io.sendEvents()`

- apps/webapp/app/db.server.ts
- apps/webapp/app/models/task.server.ts
- apps/webapp/app/platform/zodWorker.server.ts
- apps/webapp/app/routes/api.v1.runs.$runId.tasks.ts
- apps/webapp/app/services/logger.server.ts
- apps/webapp/app/services/tasks/runTask.server.ts
- packages/core/src/logger.ts
- pnpm-lock.yaml
- references/job-catalog/src/edge-cases.ts
---
I tested all the built-in jobs and the edge case jobs in the job reference, and all the task stuff still worked.
---
Removed a bunch of the work that was happening inside the run task transaction that didn't really need to be there, and streamlined the task creation. I also added tracing ability to the logger so we can include the handled job in all log messages while a graphile job is being run, which will make tracking down errors easier.
> Fix “transaction already closed” error when running tasks

- docs/integrations/apis/openai/assistants.mdx
> Fix spelling in OpenAI Assistants

- apps/webapp/app/platform/zodWorker.server.ts
This reverts commit e8e7c116d192095bd2e0d61a196538fd5a5d9039.
---
---
---
💯
> Revert "Remove the pg listen code to see if it’s causing DB issues"

- .changeset/eleven-ghosts-applaud.md
- apps/webapp/app/routes/api.v1.store.$key.ts
- packages/trigger-sdk/src/apiClient.ts
- references/job-catalog/src/built-ins.ts
Exactly what it says on the tin
> Fix: URI encode KV store keys

- .changeset/nervous-rabbits-attend.md
- packages/testing/README.md
- packages/testing/src/index.ts
- packages/testing/tests/createJobTester.test.ts
- packages/testing/tsconfig.json
Closes #792 
---
`pnpm test --filter testing`
---
---
💯
> Fix: Test package run isolation

- .changeset/clean-gifts-swim.md
- integrations/github/package.json
- pnpm-lock.yaml
This branch relates to #807 by @iskakaushik.
It was created to fix https://github.com/advisories/GHSA-pwfr-8pq7-x9qv
> Update Octokit to account for CVE-2023-50728

- .github/workflows/publish-docker.yml
- docker/Dockerfile
Closes #817 
---
Built images and ran on ARM system with the standard [docker instructions](https://github.com/triggerdotdev/docker) - only change being the image used.
---
- Run native ARM build in parallel
- Add `-arm` postfixed tags for future builds, e.g. `v1.2.3-arm` and `latest-arm`
💯
> Feature: ARM builds

- .changeset/nine-trainers-vanish.md
- apps/webapp/app/routes/api.v1.jobs.$jobSlug.cancel-runs.ts
- apps/webapp/app/services/jobs/cancelRunsForJob.server.ts
- packages/core/src/schemas/index.ts
- packages/core/src/schemas/jobs.ts
- packages/trigger-sdk/src/apiClient.ts
- packages/trigger-sdk/src/triggerClient.ts
Closes #756
---
Add ```cancelRunsForJob('<your_job_id>')``` to SDK
> feat: Add ability to cancel all runs for job from SDK

- docs/_snippets/manual-setup-express.mdx
Related #769 
---
Add a comment explaining that for Express, any JSON parser middlewares need to be registered after the Trigger middleware.
---
💯
> docs: Add comment to when using as Express middleware

- apps/webapp/app/components/event/EventDetail.tsx
- apps/webapp/app/components/events/EventsTable.tsx
- apps/webapp/app/presenters/EventListPresenter.server.ts
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.jobs.$jobParam._index/ListPagination.tsx
- Don't show internal events (like Invoke and webhook registration events)
- Show the cancelled date
- Made the pagination component accept any List type
- Improved a bit of wording
> Event page tweaks

- docs/documentation/guides/self-hosting/kubernetes.mdx
- helm-charts/.helmignore
- helm-charts/README.md
- helm-charts/my-values.yml
- helm-charts/package-lock.json
- helm-charts/package.json
- helm-charts/templates/trigger.yaml
- helm-charts/values.yaml
---
Deployed to cluster with updated instructions.
---
- Auto-generate parameters docs
- Move env vars to `trigger.env`
- Add helm and kubectl commands to docs
💯
> Fix: helm chart and docs

- docs/sdk/io/runtask.mdx
> fix(docs): fix syntax error

- .changeset/quick-experts-own.md
- integrations/resend/src/index.ts
---
Fix resend integration example comment
> fix: Resend integration example comment

- apps/webapp/app/services/runs/continueRun.server.ts
Closes #867
---
Allow retrying a job run with an invalid payload
💯
> fix: "Retry job run" fails if the job has an invalid payload

- apps/webapp/app/presenters/v3/SpanPresenter.server.ts
- apps/webapp/app/routes/api.v1.projects.$projectRef.envvars.ts
- apps/webapp/app/v3/authenticatedSocketConnection.server.ts
- apps/webapp/app/v3/environmentVariables/environmentVariablesRepository.server.ts
- apps/webapp/app/v3/environmentVariables/repository.ts
- apps/webapp/app/v3/marqs/devQueueConsumer.server.ts
- packages/cli-v3/src/apiClient.ts
- packages/cli-v3/src/commands/dev.tsx
- packages/cli-v3/src/dev/backgroundWorker.ts
- packages/core/src/v3/schemas/api.ts
- packages/core/src/v3/schemas/messages.ts
- pnpm-lock.yaml
- references/v3-catalog/package.json
- references/v3-catalog/src/stripeUsage.ts
- references/v3-catalog/src/trigger/stripe.ts
Using the new env var support in v3, this will pull the dev env vars saved on the server when indexing and running tasks
> v3: Override local env vars with env vars in the server

- apps/webapp/app/components/code/codeMirrorTheme.ts
- apps/webapp/app/components/navigation/SideMenu.tsx
- apps/webapp/app/components/primitives/RadioButton.tsx
- apps/webapp/app/components/runs/v3/TaskRunStatus.tsx
- apps/webapp/app/components/stories/RadioGroup.stories.tsx
- apps/webapp/app/models/runtimeEnvironment.server.ts
- apps/webapp/app/presenters/v3/RunListPresenter.server.ts
- apps/webapp/app/presenters/v3/TestPresenter.server.ts
- apps/webapp/app/presenters/v3/TestTaskPresenter.server.ts
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.test.tasks.$taskParam/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.test/route.tsx
- apps/webapp/app/utils/pathBuilder.ts
- apps/webapp/app/v3/services/createBackgroundWorker.server.ts
- apps/webapp/app/v3/services/testTask.server.ts
- apps/webapp/app/v3/services/triggerTask.server.ts
- packages/database/prisma/migrations/20240227144742_task_run_added_is_test/migration.sql
- packages/database/prisma/schema.prisma
You can now test v3 tasks, with support for selecting recent payloads.
> V3 Test feature

- apps/coordinator/src/index.ts
- apps/webapp/app/routes/api.v1.deployments.$deploymentId.ts
- apps/webapp/app/v3/handleSocketIo.server.ts
- apps/webapp/app/v3/services/deploymentIndexFailed.server.ts
- packages/cli-v3/src/commands/deploy.ts
- packages/cli-v3/src/commands/dev.tsx
- packages/cli-v3/src/workers/common/errors.ts
- packages/cli-v3/src/workers/common/worker-setup.ts
- packages/cli-v3/src/workers/dev/backgroundWorker.ts
- packages/cli-v3/src/workers/dev/worker-facade.ts
- packages/cli-v3/src/workers/prod/backgroundWorker.ts
- packages/cli-v3/src/workers/prod/entry-point.ts
- packages/cli-v3/src/workers/prod/worker-facade.ts
- packages/cli-v3/tsup.workers.config.ts
- packages/core/src/v3/schemas/api.ts
- packages/core/src/v3/schemas/messages.ts
- packages/core/src/v3/schemas/schemas.ts
- packages/database/prisma/migrations/20240308203644_add_deployment_error_columns/migration.sql
- packages/database/prisma/schema.prisma
https://github.com/triggerdotdev/trigger.dev/assets/534/5382cce4-9960-426c-bde0-ca7d25f231e8
> v3: Capture uncaught exceptions during indexing and fail deploys

- apps/webapp/app/routes/projects.v3.$projectRef.deployments.$deploymentParam.ts
- apps/webapp/app/v3/environmentVariables/environmentVariablesRepository.server.ts
- apps/webapp/app/v3/services/initializeDeployment.server.ts
- packages/cli-v3/src/commands/deploy.ts
- packages/cli-v3/src/utilities/session.ts
- packages/core/src/v3/schemas/api.ts
- packages/database/prisma/migrations/20240311135706_add_triggered_by_to_deployments/migration.sql
- packages/database/prisma/schema.prisma
- Cache dependency resolution step
- Added a "triggered by" relationship to deployments
- Fixed an issue when deleting env vars that would prevent them from being recreated
- Better deploy output, including linking to the deployment page
> v3: various deploy improvements

- apps/webapp/app/components/navigation/SideMenu.tsx
- apps/webapp/app/components/primitives/Badge.tsx
- apps/webapp/app/components/primitives/Pagination.tsx
- apps/webapp/app/components/primitives/PropertyTable.tsx
- apps/webapp/app/components/runs/v3/DeploymentStatus.tsx
- apps/webapp/app/components/runs/v3/TaskPath.tsx
- apps/webapp/app/consts.ts
- apps/webapp/app/presenters/v3/DeploymentListPresenter.server.ts
- apps/webapp/app/presenters/v3/DeploymentPresenter.server.ts
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.deployments.$deploymentParam/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.deployments/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam.spans.$spanParam/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.test/route.tsx
- apps/webapp/app/utils/pathBuilder.ts
- apps/webapp/app/utils/searchParams.ts
- apps/webapp/app/v3/services/createDeployedBackgroundWorker.server.ts
- The deployments table
- Selected deployment details
- Promoted deployment getting upserted with the "current" label
https://github.com/triggerdotdev/trigger.dev/assets/10635986/62c01e8d-675e-4b09-afd3-47d4a121f7f1
> v3 deployments page

- apps/webapp/app/components/primitives/Buttons.tsx
- apps/webapp/app/components/runs/v3/SpanTitle.tsx
- apps/webapp/app/presenters/v3/SpanPresenter.server.ts
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.deployments/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam.spans.$spanParam/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam/route.tsx
- apps/webapp/app/routes/resources.taskruns.$runParam.cancel.ts
- apps/webapp/app/v3/eventRepository.server.ts
- apps/webapp/app/v3/services/triggerTask.server.ts
- packages/core/src/v3/semanticInternalAttributes.ts
- Cancel a run from the span view
- Focus on a child span
- Go to parent with the focus being kept on the selected span
- Shortcut keys
> Cancel a run from the span view

- apps/webapp/app/presenters/v3/TasksStreamPresenter.server.ts
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam._index/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.tasks.stream/route.tsx
- apps/webapp/app/utils/pathBuilder.ts
- apps/webapp/app/v3/marqs/devPubSub.server.ts
- apps/webapp/app/v3/services/createBackgroundWorker.server.ts
- apps/webapp/app/v3/services/createDeployedBackgroundWorker.server.ts
- apps/webapp/app/v3/services/projectPubSub.server.ts
When there are new tasks the tasks page live reloads.
- Can either be tasks from the CLI or deployed tasks
> Tasks page live-reloads with new tasks

- apps/webapp/app/components/Feedback.tsx
- apps/webapp/app/components/primitives/PageHeader.tsx
- apps/webapp/app/components/primitives/Select.tsx
- apps/webapp/app/components/primitives/Tooltip.tsx
- apps/webapp/app/components/runs/v3/RunFilters.tsx
- apps/webapp/app/components/runs/v3/TaskRunAttemptStatus.tsx
- apps/webapp/app/components/runs/v3/TaskRunStatus.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.integrations/route.tsx
- apps/webapp/app/routes/resources.feedback.ts
- apps/webapp/app/routes/storybook.loading-bar-divider/route.tsx
- apps/webapp/app/routes/storybook/route.tsx
- added loading bar animation to storybook
- better and more useful feedback sheet with feedback button in top right if you're on a v3 project
- Dropdown status menu shows tool tips on hover
> V3 UI improvements

- apps/webapp/app/components/Feedback.tsx
- apps/webapp/app/components/navigation/SideMenu.tsx
- apps/webapp/app/components/primitives/PageHeader.tsx
- Moved the v3 feedback button from PageHeader to SideMenu
- Fixed small issue with buttons not wrapping on the feedback Sheet
> Improved v3 feedback button

- apps/webapp/app/components/runs/v3/DeploymentStatus.tsx
- apps/webapp/app/presenters/v3/DeploymentPresenter.server.ts
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.deployments.$deploymentParam/route.tsx
- apps/webapp/app/services/worker.server.ts
- apps/webapp/app/v3/marqs/sharedQueueConsumer.server.ts
- apps/webapp/app/v3/models/workerDeployment.server.ts
- apps/webapp/app/v3/services/createCheckpointRestoreEvent.server.ts
- apps/webapp/app/v3/services/createDeployedBackgroundWorker.server.ts
- apps/webapp/app/v3/services/indexDeployment.server.ts
- apps/webapp/app/v3/services/initializeDeployment.server.ts
- apps/webapp/app/v3/services/startDeploymentIndexing.server.ts
- apps/webapp/app/v3/services/timeoutDeployment.server.ts
- packages/cli-v3/src/commands/deploy.ts
- packages/cli-v3/src/commands/whoami.ts
- packages/core/src/v3/schemas/api.ts
- packages/database/prisma/migrations/20240320100720_add_timed_out_status_to_deployments/migration.sql
- packages/database/prisma/schema.prisma
- Time out deployments to prevent never-ending building/deploying
- Use the CURRENT worker deployment when determining which version to execute
- Fix some of the deployment error handling logic
> v3: A bunch of deployment fixes

- packages/core/src/v3/schemas/messages.ts
- packages/core/src/v3/types/index.ts
- packages/trigger-sdk/src/v3/shared.ts
- packages/trigger-sdk/src/v3/tasks.ts
Started adding some JSDocs for the v3 SDK
- Task and the options
> Basic JSDocs for the v3 SDK

- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.triggers._index/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.triggers.scheduled/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.triggers.webhooks/route.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.triggers/route.tsx
- fix for the Triggers pages not scrolling. All 3 page tabs now scroll.
> Fixed Triggers pages not scrolling

- apps/webapp/app/components/navigation/SideMenu.tsx
- apps/webapp/app/components/primitives/Dialog.tsx
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.environment-variables.new/route.tsx
- Toggle password visiblility of the env var inputs 
- Label to show what project version you're in
- Shows a 'request access to v3' button if you're on a v2 project. It links to the marketing site sign up form.
> V3 project labels

- .changeset/rare-roses-float.md
- packages/cli-v3/src/Containerfile.prod
- packages/cli-v3/src/commands/login.ts
> v3: add openssl to prod image and fix deploy command auth via env var

- docs/v3/github-actions.mdx
---
NA: Just a minor docs change
---
- Added example of github workflow for deploying staging
---
💯
> Added example of github workflow for deploy to staging

- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.environment-variables.new/route.tsx
- apps/webapp/package.json
- apps/webapp/remix.config.js
- pnpm-lock.yaml
- Use the dotenv package for paste support (works with quoted strings and anything else that's supported in .env)
- Make the panel wider on larger screens
> Environment variables pasting uses dotenv

- docs/integrations/apis/supabase/management.mdx
Adding note for custom domains and initializing db object.
---
n/a -- was a README change
---
n/a
added a note about the supabase integration and custom domains.
---
n/a
> Adding note for supabase integration

- apps/proxy/package.json
- apps/proxy/src/index.ts
- apps/proxy/src/rateLimit.ts
- apps/proxy/src/rateLimiter.ts
- apps/proxy/wrangler.toml
- pnpm-lock.yaml
The proxy now has a rate limit using Cloudflare's new rate limit feature.
> Proxy rate limit

- apps/webapp/app/presenters/JobListPresenter.server.ts
- apps/webapp/app/presenters/JobPresenter.server.ts
- apps/webapp/app/presenters/OrgBillingPlanPresenter.ts
- apps/webapp/app/presenters/OrgUsagePresenter.server.ts
- apps/webapp/app/presenters/RunListPresenter.server.ts
- apps/webapp/app/presenters/v3/ScheduleListPresenter.server.ts
- apps/webapp/app/routes/api.v2.events.$eventId.ts
- apps/webapp/app/services/billing.server.ts
- apps/webapp/app/v3/eventRepository.server.ts
Switch the slowest queries to use the read replica where possible
> Use the read replica more

- apps/webapp/app/models/endpoint.server.ts
Closes #1161
---
Deployed on render.com and it worked.
---
fix: cloudfront timeouts not being caught
---
💯
> fix: cloudfront timeouts not being caught

- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs._index/route.tsx
Updated the bulk action bar UI to stand out more: 
- Bigger buttons
- New left hand colour icon
- Buttons have colour icons
- Taller action bar 
- Also, small improvement to the button size and text in the confirm modals for Replay and Cancel
> Made the bulk action bar taller, bigger buttons and more colour.

- apps/webapp/app/components/primitives/Buttons.tsx
- apps/webapp/app/components/runs/v3/ReplayRunDialog.tsx
- apps/webapp/app/lib.es5.d.ts
- apps/webapp/app/presenters/v3/RunPresenter.server.ts
- apps/webapp/app/presenters/v3/SpanPresenter.server.ts
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam/route.tsx
- apps/webapp/app/routes/resources.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam.spans.$spanParam/route.tsx
- apps/webapp/app/services/worker.server.ts
- apps/webapp/app/v3/eventRepository.server.ts
- packages/database/prisma/migrations/20240804143817_add_task_run_logs_deleted_at_column/migration.sql
- packages/database/prisma/schema.prisma
When your run logs have been deleted you can now see the run inspector with the status, dates, payload, output, error, etc.
Also added some extra columns required to be a better job of log deletion.
> Improved the experience when you have no run logs

- apps/webapp/app/presenters/v3/SpanPresenter.server.ts
- apps/webapp/app/routes/resources.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam.spans.$spanParam/route.tsx
They were only showing when there were still span events…
Also improved the display of them using our error types
> Show errors in the Run inspector when the logs have been deleted

- apps/webapp/app/components/navigation/SideMenu.tsx
- apps/webapp/app/presenters/JobPresenter.server.ts
- apps/webapp/app/presenters/OrganizationsPresenter.server.ts
- apps/webapp/app/presenters/ProjectPresenter.server.ts
- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.jobs.$jobParam/route.tsx
- packages/database/prisma/migrations/20240821135542_job_run_index_for_organization_id_and_created_at/migration.sql
- packages/database/prisma/migrations/20240821141347_job_run_index_version_id/migration.sql
- packages/database/prisma/migrations/20240821142006_batch_task_run_item_index_task_run_attempt_id/migration.sql
- packages/database/prisma/migrations/20240821142353_batch_task_run_item_index_task_run_id/migration.sql
- packages/database/prisma/schema.prisma
- Removed some counts that were being used for v2 onboarding that were severely impacting performance.
- Added indexes for JobRun and BatchTaskRunitem
> Dashboard query improvements

- .vscode/extensions.json
---
---
Removed a VS Code recommended extension that is no longer needed.
---
💯
> Remove astro as recommended extension

- apps/docker-provider/src/index.ts
---
😅
---
Made the hard coded docker `host` network, configurable via environmental parameters.
---
None
💯
> Allow custom docker network

- apps/webapp/app/components/runs/v3/RunInspector.tsx
- apps/webapp/app/components/runs/v3/SpanInspector.tsx
- apps/webapp/app/routes/resources.orgs.$organizationSlug.projects.v3.$projectParam.runs.$runParam.spans.$spanParam/route.tsx
Small bug fix that means the tabs now horizontally scroll when the right side panel is resized very narrow.
> Tabs horizontally scroll in the side panel inspectors

- apps/webapp/app/routes/resources.$organizationSlug.subscription.portal.ts
The Stripe "Invoices" and "Manage card details" buttons were pointing at a moved page
> Update the file path for the Stripe subcription portal

- apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.env.$envParam.waitpoints.tokens/route.tsx
Adds a selected state on the waitpoints table rows
> Waitpoints: Adds selected state on the table rows

- pnpm-lock.yaml
- references/nextjs-realtime/package.json
> Release 4.0.0-v4-beta.0

- .changeset/big-carrots-fail.md
- packages/cli-v3/src/dev/backgroundWorker.ts
This fixes an indexing regression after recent changes. It should only affect dev runs.
> Fix dev indexing

- apps/webapp/app/components/AskAI.tsx
- apps/webapp/app/components/navigation/SideMenu.tsx
- apps/webapp/app/root.tsx
Use `ClientOnly`, fix for the ai search param not working
> Fix for the Kapa widget not working with SSR

- docs/tags.mdx
Update number of allowed tags from 5 to 10
> Docs: Update number of allowed tags from 5 to 10

- hosting/k8s/helm/Chart.yaml
- hosting/k8s/helm/templates/_helpers.tpl
- hosting/k8s/helm/templates/supervisor.yaml
- hosting/k8s/helm/values.yaml
Switch from ClusterRole -> Role (non-breaking)
> Switch trigger Helm chart RBAC from cluster to namespace scope and bump version

- hosting/docker/webapp/docker-compose.yml
- hosting/k8s/helm/Chart.yaml
- hosting/k8s/helm/values.yaml
Also makes the docker setup use the new cli tag override. This fixes the commands displayed in the webapp.
> Update self hosting images to beta.22

- apps/webapp/app/v3/marqs/index.server.ts
More telemetry to figure out why dequeuing is slow
> Add attemptDequeue span to marqs
